--------------------------------------------------------
--  File created - Saturday-June-08-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence PHONGBAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PHONGBAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NHANVIEN
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_NHANVIEN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 49 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BANGLUONG
--------------------------------------------------------

  CREATE TABLE "BANGLUONG" 
   (	"MABL" NUMBER(*,0), 
	"MANV" NUMBER(*,0), 
	"NAM" NUMBER(*,0), 
	"THANG" NUMBER(*,0), 
	"TONGTIENUL" NUMBER, 
	"LUONGTL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NHANVIEN
--------------------------------------------------------

  CREATE TABLE "NHANVIEN" 
   (	"MANV" NUMBER(*,0), 
	"MAPB" CHAR(4 BYTE), 
	"TENNV" VARCHAR2(30 BYTE), 
	"CCCD" CHAR(12 BYTE), 
	"NGSINH" DATE, 
	"QUEQUAN" VARCHAR2(30 BYTE), 
	"GIOITINH" NUMBER(*,0), 
	"CHUCVU" VARCHAR2(20 BYTE), 
	"LUONGCB" NUMBER, 
	"HESO" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHIEUCHAMCONG
--------------------------------------------------------

  CREATE TABLE "PHIEUCHAMCONG" 
   (	"MAPCC" NUMBER(*,0), 
	"MANV" NUMBER(*,0), 
	"NGAYCC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHONGBAN
--------------------------------------------------------

  CREATE TABLE "PHONGBAN" 
   (	"MAPB" CHAR(4 BYTE), 
	"TENPB" VARCHAR2(30 BYTE), 
	"NGAYTL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAIKHOAN
--------------------------------------------------------

  CREATE TABLE "TAIKHOAN" 
   (	"TENTK" CHAR(20 BYTE), 
	"MANV" NUMBER(*,0), 
	"MATKHAU" CHAR(20 BYTE), 
	"LOAITK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRUONGPHONG
--------------------------------------------------------

  CREATE TABLE "TRUONGPHONG" 
   (	"MANV" NUMBER(*,0), 
	"MAPB" CHAR(4 BYTE), 
	"NGAYNC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table YEUCAUNGHIPHEP
--------------------------------------------------------

  CREATE TABLE "YEUCAUNGHIPHEP" 
   (	"MAYCNP" NUMBER(*,0), 
	"MANV" NUMBER(*,0), 
	"NGAYGUI" DATE, 
	"NGAYBD" DATE, 
	"NGAYKT" DATE, 
	"GHICHUNP" VARCHAR2(100 BYTE), 
	"TRANGTHAINP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table YEUCAUUNGLUONG
--------------------------------------------------------

  CREATE TABLE "YEUCAUUNGLUONG" 
   (	"MAYCUL" NUMBER(*,0), 
	"MANV" NUMBER(*,0), 
	"NGAYUL" DATE, 
	"TIENUL" NUMBER, 
	"GHICHUUL" VARCHAR2(50 BYTE), 
	"TRANGTHAIUL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BANGLUONG
SET DEFINE OFF;
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (16,1,2024,6,0,600);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (1,1,2023,5,1000000,35000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (2,2,2023,5,2000000,32000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (3,3,2023,5,500000,20000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (4,4,2023,5,700000,19000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (5,5,2023,5,300000,16000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (6,6,2023,5,1000000,25000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (7,7,2023,5,2000000,22000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (8,8,2023,5,500000,23000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (9,1,2023,6,1500000,38000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (10,2,2023,6,700000,33000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (11,3,2023,6,1200000,21000000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (12,4,2023,6,300000,19700000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (13,5,2023,6,600000,30300000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (14,6,2023,6,800000,27200000);
Insert into BANGLUONG (MABL,MANV,NAM,THANG,TONGTIENUL,LUONGTL) values (15,7,2023,6,1000000,22400000);
REM INSERTING into NHANVIEN
SET DEFINE OFF;
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (6,'PB01','L� Ng?c Di?p','079201018989',to_date('18-FEB-87','DD-MON-RR'),'H� N?i',0,'Th? k�',18000000,1.8);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (7,'PB03','Tr?n V?n H�','079451018989',to_date('12-AUG-93','DD-MON-RR'),'Qu?ng B�nh',1,'Nh�n vi�n',14000000,1.6);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (8,'PB04','Nguy?n Mai Anh','079453456789',to_date('28-APR-86','DD-MON-RR'),'H� N?i',0,'Nh�n vi�n',16000000,1.85);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (1,'PB01','Nguy?n V?n A','012345678901',to_date('15-MAY-90','DD-MON-RR'),'H� N?i',1,'Tr??ng ph�ng',15000,1.5);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (2,'PB01','Tr?n Th? B','023456789012',to_date('28-FEB-95','DD-MON-RR'),'TP. H? Ch� Minh',0,'Nh�n vi�n',10000,1.2);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (3,'PB02','L� V?n C','034567890123',to_date('10-NOV-88','DD-MON-RR'),'?� N?ng',1,'Ph� ph�ng',12000,1.3);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (4,'PB02','Ph?m Th? D','045678901234',to_date('03-AUG-92','DD-MON-RR'),'H?i Ph�ng',0,'Nh�n vi�n',9000,1.1);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (5,'PB03','Ho�ng V?n E','056789012345',to_date('22-MAR-85','DD-MON-RR'),'C?n Th?',1,'Tr??ng ph�ng',18000,1.8);
Insert into NHANVIEN (MANV,MAPB,TENNV,CCCD,NGSINH,QUEQUAN,GIOITINH,CHUCVU,LUONGCB,HESO) values (30,'PB01','Tr?n T?n T�i','087204356123',to_date('10-JUN-04','DD-MON-RR'),'H? Ch� Minh',1,'Tr??ng ph�ng',60000000,1);
REM INSERTING into PHIEUCHAMCONG
SET DEFINE OFF;
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (1,1,to_date('01-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (2,1,to_date('02-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (3,1,to_date('03-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (4,1,to_date('04-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (5,1,to_date('05-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (6,1,to_date('06-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (7,1,to_date('07-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (8,1,to_date('08-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (9,1,to_date('09-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (10,1,to_date('10-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (11,2,to_date('15-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (12,2,to_date('22-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (13,2,to_date('05-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (14,2,to_date('29-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (15,2,to_date('18-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (16,2,to_date('11-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (17,2,to_date('27-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (18,2,to_date('03-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (19,2,to_date('24-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (20,2,to_date('07-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (21,3,to_date('12-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (22,3,to_date('26-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (23,3,to_date('19-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (24,3,to_date('04-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (25,3,to_date('31-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (26,3,to_date('14-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (27,3,to_date('08-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (28,3,to_date('23-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (29,3,to_date('17-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (30,3,to_date('30-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (31,4,to_date('06-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (32,4,to_date('21-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (33,4,to_date('28-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (34,4,to_date('13-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (35,4,to_date('02-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (36,4,to_date('16-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (37,4,to_date('25-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (38,4,to_date('09-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (39,4,to_date('20-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (40,4,to_date('01-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (41,5,to_date('11-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (42,5,to_date('22-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (43,5,to_date('03-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (44,5,to_date('29-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (45,5,to_date('18-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (46,5,to_date('07-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (47,5,to_date('24-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (48,5,to_date('15-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (49,5,to_date('30-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (50,5,to_date('05-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (51,6,to_date('27-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (52,6,to_date('10-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (53,6,to_date('17-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (54,6,to_date('04-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (55,6,to_date('23-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (56,6,to_date('14-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (57,6,to_date('31-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (58,6,to_date('08-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (59,6,to_date('19-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (60,6,to_date('01-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (61,7,to_date('13-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (62,7,to_date('26-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (63,7,to_date('07-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (64,7,to_date('20-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (65,7,to_date('02-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (66,7,to_date('29-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (67,7,to_date('16-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (68,7,to_date('09-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (69,7,to_date('22-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (70,7,to_date('05-MAY-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (72,1,to_date('04-JUN-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (73,2,to_date('04-JUN-24','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (74,1,to_date('01-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (75,1,to_date('02-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (76,1,to_date('03-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (77,1,to_date('04-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (78,1,to_date('05-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (79,1,to_date('06-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (80,1,to_date('07-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (81,1,to_date('08-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (82,1,to_date('09-JUN-23','DD-MON-RR'));
Insert into PHIEUCHAMCONG (MAPCC,MANV,NGAYCC) values (83,1,to_date('10-JUN-23','DD-MON-RR'));
REM INSERTING into PHONGBAN
SET DEFINE OFF;
Insert into PHONGBAN (MAPB,TENPB,NGAYTL) values ('PB04','Ph�ng Nh�n S?',to_date('25-AUG-11','DD-MON-RR'));
Insert into PHONGBAN (MAPB,TENPB,NGAYTL) values ('PB05','Ph�ng IT',to_date('20-OCT-22','DD-MON-RR'));
Insert into PHONGBAN (MAPB,TENPB,NGAYTL) values ('PB01','Ph�ng Nh�n s?',to_date('01-JAN-20','DD-MON-RR'));
Insert into PHONGBAN (MAPB,TENPB,NGAYTL) values ('PB02','Ph�ng K? to�n',to_date('15-JUN-19','DD-MON-RR'));
Insert into PHONGBAN (MAPB,TENPB,NGAYTL) values ('PB03','Ph�ng Marketing',to_date('10-MAR-21','DD-MON-RR'));
Insert into PHONGBAN (MAPB,TENPB,NGAYTL) values ('PB06','Ph�ng Culi',to_date('04-JUN-24','DD-MON-RR'));
REM INSERTING into TAIKHOAN
SET DEFINE OFF;
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('daoxuanhai1         ',1,'daoxuanhai1         ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('daoxuanhaiAD        ',1,'daoxuanhaiAD        ',1);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('buimyhi2            ',2,'buimyhi2            ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('trantanphuc3        ',3,'trantanphuc3        ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('maivietanh4         ',4,'maivietanh4         ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('maivietanhAD        ',4,'maivietanhAD        ',1);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('vuducanh5           ',5,'vuducanh5           ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('lengocdiep6         ',6,'lengocdiep6         ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('tranvanha7          ',7,'tranvanha7          ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('nguy?nmaianh8     ',8,'nguy?nmaianh8     ',0);
Insert into TAIKHOAN (TENTK,MANV,MATKHAU,LOAITK) values ('trantantai30        ',30,'trantantai30        ',0);
REM INSERTING into TRUONGPHONG
SET DEFINE OFF;
Insert into TRUONGPHONG (MANV,MAPB,NGAYNC) values (2,'PB02',to_date('01-JUN-15','DD-MON-RR'));
Insert into TRUONGPHONG (MANV,MAPB,NGAYNC) values (1,'PB01',to_date('15-MAR-18','DD-MON-RR'));
Insert into TRUONGPHONG (MANV,MAPB,NGAYNC) values (5,'PB04',to_date('20-SEP-20','DD-MON-RR'));
Insert into TRUONGPHONG (MANV,MAPB,NGAYNC) values (4,'PB03',to_date('10-NOV-17','DD-MON-RR'));
REM INSERTING into YEUCAUNGHIPHEP
SET DEFINE OFF;
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (1,1,to_date('15-MAY-23','DD-MON-RR'),to_date('01-JUN-23','DD-MON-RR'),to_date('10-JUN-23','DD-MON-RR'),'Ngh? ph�p n?m','?� ph� duy?t');
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (2,3,to_date('20-APR-23','DD-MON-RR'),to_date('01-MAY-23','DD-MON-RR'),to_date('05-MAY-23','DD-MON-RR'),'Ngh? l?','Ch? ph� duy?t');
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (3,5,to_date('10-MAR-23','DD-MON-RR'),to_date('01-APR-23','DD-MON-RR'),to_date('15-APR-23','DD-MON-RR'),'Tham d? c�ng vi?c b�n ngo�i','Ch? ph� duy?t');
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (4,7,to_date('01-MAY-23','DD-MON-RR'),to_date('15-MAY-23','DD-MON-RR'),to_date('20-MAY-23','DD-MON-RR'),'Vi?c c� nh�n ??t xu?t','?� h?y');
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (6,2,to_date('15-APR-23','DD-MON-RR'),to_date('01-MAY-23','DD-MON-RR'),to_date('15-MAY-23','DD-MON-RR'),'Ngh? ph�p n?m','Ch? ph� duy?t');
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (7,6,to_date('10-JUN-23','DD-MON-RR'),to_date('01-JUL-23','DD-MON-RR'),to_date('15-JUL-23','DD-MON-RR'),'Vi?c c� nh�n','Ch? ph� duy?t');
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (8,8,to_date('20-MAY-23','DD-MON-RR'),to_date('01-JUN-23','DD-MON-RR'),to_date('10-JUN-23','DD-MON-RR'),'Chu?n b? s? ki?n k? ni?m c�ng ty','Ch? ph� duy?t');
Insert into YEUCAUNGHIPHEP (MAYCNP,MANV,NGAYGUI,NGAYBD,NGAYKT,GHICHUNP,TRANGTHAINP) values (9,1,to_date('04-JUN-24','DD-MON-RR'),to_date('05-JUN-24','DD-MON-RR'),to_date('06-JUN-24','DD-MON-RR'),'Ngh? ?? ','Ch? ph� duy?t');
REM INSERTING into YEUCAUUNGLUONG
SET DEFINE OFF;
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (1,1,to_date('15-APR-23','DD-MON-RR'),1000000,'L� do c� nh�n','?� ph� duy?t');
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (2,3,to_date('20-MAR-23','DD-MON-RR'),800000,'Mua v?t d?ng ph�ng ban','?� ph� duy?t');
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (3,5,to_date('10-MAY-23','DD-MON-RR'),1200000,'L� do c� nh�n','Ch? ph� duy?t');
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (4,7,to_date('28-FEB-23','DD-MON-RR'),700000,'L� do c� nh�n','T? ch?i');
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (6,2,to_date('01-JUN-23','DD-MON-RR'),2000000,'Chi tr? vi?n ph�','Ch? ph� duy?t');
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (7,4,to_date('10-MAR-23','DD-MON-RR'),1800000,'L� do c� nh�n','Ch? ph� duy?t');
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (8,6,to_date('20-MAY-23','DD-MON-RR'),900000,'L? ph� c�ng t�c','Ch? ph� duy?t');
Insert into YEUCAUUNGLUONG (MAYCUL,MANV,NGAYUL,TIENUL,GHICHUUL,TRANGTHAIUL) values (9,1,to_date('04-JUN-24','DD-MON-RR'),1500,'Ti?n ?? ','Ch? ph� duy?t');
--------------------------------------------------------
--  DDL for Index DUOCCAP_FK
--------------------------------------------------------

  CREATE INDEX "DUOCCAP_FK" ON "TAIKHOAN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GUI_FK
--------------------------------------------------------

  CREATE INDEX "GUI_FK" ON "YEUCAUNGHIPHEP" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KHAIBAO_FK
--------------------------------------------------------

  CREATE INDEX "KHAIBAO_FK" ON "PHIEUCHAMCONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LAMVIEC_FK
--------------------------------------------------------

  CREATE INDEX "LAMVIEC_FK" ON "NHANVIEN" ("MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BANGLUONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BANGLUONG" ON "BANGLUONG" ("MABL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_NHANVIEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_NHANVIEN" ON "NHANVIEN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PHIEUCHAMCONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PHIEUCHAMCONG" ON "PHIEUCHAMCONG" ("MAPCC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PHONGBAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PHONGBAN" ON "PHONGBAN" ("MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TAIKHOAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TAIKHOAN" ON "TAIKHOAN" ("TENTK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRUONGPHONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRUONGPHONG" ON "TRUONGPHONG" ("MANV", "MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_YEUCAUNGHIPHEP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_YEUCAUNGHIPHEP" ON "YEUCAUNGHIPHEP" ("MAYCNP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_YEUCAUUNGLUONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_YEUCAUUNGLUONG" ON "YEUCAUUNGLUONG" ("MAYCUL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOHUU_FK
--------------------------------------------------------

  CREATE INDEX "SOHUU_FK" ON "BANGLUONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index THUCHIEN_FK
--------------------------------------------------------

  CREATE INDEX "THUCHIEN_FK" ON "YEUCAUUNGLUONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRUONGPHONG2_FK
--------------------------------------------------------

  CREATE INDEX "TRUONGPHONG2_FK" ON "TRUONGPHONG" ("MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRUONGPHONG_FK
--------------------------------------------------------

  CREATE INDEX "TRUONGPHONG_FK" ON "TRUONGPHONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BANGLUONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BANGLUONG" ON "BANGLUONG" ("MABL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOHUU_FK
--------------------------------------------------------

  CREATE INDEX "SOHUU_FK" ON "BANGLUONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_NHANVIEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_NHANVIEN" ON "NHANVIEN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LAMVIEC_FK
--------------------------------------------------------

  CREATE INDEX "LAMVIEC_FK" ON "NHANVIEN" ("MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PHIEUCHAMCONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PHIEUCHAMCONG" ON "PHIEUCHAMCONG" ("MAPCC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KHAIBAO_FK
--------------------------------------------------------

  CREATE INDEX "KHAIBAO_FK" ON "PHIEUCHAMCONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PHONGBAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PHONGBAN" ON "PHONGBAN" ("MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TAIKHOAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TAIKHOAN" ON "TAIKHOAN" ("TENTK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DUOCCAP_FK
--------------------------------------------------------

  CREATE INDEX "DUOCCAP_FK" ON "TAIKHOAN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRUONGPHONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRUONGPHONG" ON "TRUONGPHONG" ("MANV", "MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRUONGPHONG_FK
--------------------------------------------------------

  CREATE INDEX "TRUONGPHONG_FK" ON "TRUONGPHONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRUONGPHONG2_FK
--------------------------------------------------------

  CREATE INDEX "TRUONGPHONG2_FK" ON "TRUONGPHONG" ("MAPB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_YEUCAUNGHIPHEP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_YEUCAUNGHIPHEP" ON "YEUCAUNGHIPHEP" ("MAYCNP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GUI_FK
--------------------------------------------------------

  CREATE INDEX "GUI_FK" ON "YEUCAUNGHIPHEP" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_YEUCAUUNGLUONG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_YEUCAUUNGLUONG" ON "YEUCAUUNGLUONG" ("MAYCUL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index THUCHIEN_FK
--------------------------------------------------------

  CREATE INDEX "THUCHIEN_FK" ON "YEUCAUUNGLUONG" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PREVENT_DELETE_PHONGBAN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREVENT_DELETE_PHONGBAN" 
BEFORE DELETE ON PHONGBAN
FOR EACH ROW
DECLARE
    v_count PHONGBAN.MAPB%TYPE;
BEGIN

    SELECT COUNT(*) INTO v_count FROM NHANVIEN WHERE MAPB = :OLD.MAPB;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Kh�ng th? x�a ph�ng ban v� c� nh�n vi�n li�n k?t.');
    END IF;

    SELECT COUNT(*) INTO v_count FROM TRUONGPHONG WHERE MAPB = :OLD.MAPB;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Kh�ng th? x�a ph�ng ban v� c� tr??ng ph�ng li�n k?t.');
    END IF;
END;

/
ALTER TRIGGER "PREVENT_DELETE_PHONGBAN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_AFTER_INSERT_NHANVIEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_AFTER_INSERT_NHANVIEN" 
AFTER INSERT ON NHANVIEN
FOR EACH ROW
DECLARE
    v_tentk_base VARCHAR2(50);
    v_tentk VARCHAR2(50);
    v_matkhau VARCHAR2(50);

    -- H�m chuy?n ??i k� t? ti?ng Vi?t c� d?u th�nh kh�ng d?u
    FUNCTION convert_to_ascii(p_str IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN TRANSLATE(
            p_str,
            '����������������������������������????�����������������������������??',
            'AAAAAAACEEEEIIIIDNOOOOOOUUUUYBSaaaaaaaaaaceeeeiiiionoooooouuuuyyybyDd'
        );
    END convert_to_ascii;
BEGIN
    -- Chuy?n t�n nh�n vi�n th�nh kh�ng d?u, x�a kho?ng c�ch v� kh�ng vi?t in hoa
    v_tentk_base := LOWER(REPLACE(convert_to_ascii(:NEW.TENNV), ' ', ''));

    -- T?o t�i kho?n v� m?t kh?u c? b?n cho m?i nh�n vi�n
    v_tentk := v_tentk_base || :NEW.MANV;
    v_matkhau := v_tentk;
    INSERT INTO TAIKHOAN (TENTK, MANV, MATKHAU, LOAITK) VALUES (v_tentk, :NEW.MANV, v_matkhau, 0);

    -- N?u ch?c v? l� "Tr??ng ph�ng" v� ph�ng ban l� K? to�n ho?c Nh�n s?, t?o th�m t�i kho?n qu?n tr?
    IF :NEW.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' AND (:NEW.MAPB = 'PB03' OR :NEW.MAPB = 'PB04') THEN
        v_tentk := v_tentk_base || 'AD';
        v_matkhau := v_tentk;
        INSERT INTO TAIKHOAN (TENTK, MANV, MATKHAU, LOAITK) VALUES (v_tentk, :NEW.MANV, v_matkhau, 1);
    END IF;
END;
/
ALTER TRIGGER "TRG_AFTER_INSERT_NHANVIEN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CHECK_BANGLUONG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CHECK_BANGLUONG" 
BEFORE INSERT ON BANGLUONG
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM BANGLUONG
    WHERE MANV = :NEW.MANV
      AND NAM = :NEW.NAM
      AND THANG = :NEW.THANG;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Nh�n vi�n n�y ?� c� b?ng l??ng trong th�ng v� n?m n�y.');
    END IF;
END;

/
ALTER TRIGGER "TRG_CHECK_BANGLUONG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_UPDATE_TAIKHOAN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UPDATE_TAIKHOAN" 
AFTER UPDATE OF CHUCVU ON NHANVIEN
FOR EACH ROW
DECLARE
    v_tentk_base VARCHAR2(50);
    v_tentk VARCHAR2(50);
    v_matkhau VARCHAR2(50);
    v_test CHAR(50);

    -- H�m chuy?n ??i k� t? ti?ng Vi?t c� d?u th�nh kh�ng d?u
    FUNCTION convert_to_ascii(p_str IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN TRANSLATE(
            p_str,
            '����������������������������������????�����������������������������??',
            'AAAAAAACEEEEIIIIDNOOOOOOUUUUYBSaaaaaaaaaaceeeeiiiionoooooouuuuyyybyDd'
        );
    END convert_to_ascii;

BEGIN
    -- Chuy?n t�n nh�n vi�n th�nh kh�ng d?u, x�a kho?ng c�ch v� kh�ng vi?t in hoa
    v_tentk_base := LOWER(REPLACE(convert_to_ascii(:NEW.TENNV), ' ', ''));
    v_test := v_tentk_base || 'AD';

    -- N?u ch?c v? thay ??i t? "Tr??ng ph�ng" th�nh c�c ch?c v? kh�c
    IF :OLD.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' AND :NEW.CHUCVU <> u'Tr\01b0\1edfng ph\00f2ng' THEN
        DELETE FROM PHIEUCHAMCONG WHERE MANV = :NEW.MANV;
        DELETE FROM YEUCAUNGHIPHEP WHERE MANV = :NEW.MANV;
        DELETE FROM YEUCAUUNGLUONG WHERE MANV = :NEW.MANV;
        DELETE FROM TAIKHOAN WHERE TENTK = v_test AND MANV = :NEW.MANV;
        DELETE FROM TRUONGPHONG WHERE MANV = :NEW.MANV;
    END IF;

    -- N?u ch?c v? thay ??i t? c�c ch?c v? kh�c th�nh "Tr??ng ph�ng" v� ph�ng ban h?p l?
    IF :OLD.CHUCVU != u'Tr\01b0\1edfng ph\00f2ng' AND :NEW.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' AND
       (:NEW.MAPB = 'PB03' OR :NEW.MAPB = 'PB04') THEN
        v_tentk := v_tentk_base || 'AD';
        v_matkhau := v_tentk;
        INSERT INTO TAIKHOAN (TENTK, MANV, MATKHAU, LOAITK) VALUES (v_tentk, :NEW.MANV, v_matkhau, 1);
        UPDATE TRUONGPHONG SET MANV = :NEW.MANV, NGAYNC = SYSDATE WHERE MAPB = :NEW.MAPB;
    END IF;

    -- C?p nh?t t�i kho?n c? b?n
    v_tentk := v_tentk_base || :NEW.MANV;
    v_matkhau := v_tentk;
    UPDATE TAIKHOAN
    SET TENTK = v_tentk, MATKHAU = v_matkhau
    WHERE MANV = :NEW.MANV AND LOAITK = 0;

    -- N?u ch?c v? hi?n t?i l� "Tr??ng ph�ng", c?p nh?t t�i kho?n qu?n tr?
    IF :NEW.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' THEN
        v_tentk := v_tentk_base || 'AD';
        v_matkhau := v_tentk;
        UPDATE TAIKHOAN
        SET TENTK = v_tentk, MATKHAU = v_matkhau
        WHERE MANV = :NEW.MANV AND LOAITK = 1;
    END IF;
END;
/
ALTER TRIGGER "TRG_UPDATE_TAIKHOAN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CHECK_BANGLUONG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CHECK_BANGLUONG" 
BEFORE INSERT ON BANGLUONG
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM BANGLUONG
    WHERE MANV = :NEW.MANV
      AND NAM = :NEW.NAM
      AND THANG = :NEW.THANG;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Nh�n vi�n n�y ?� c� b?ng l??ng trong th�ng v� n?m n�y.');
    END IF;
END;

/
ALTER TRIGGER "TRG_CHECK_BANGLUONG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_AFTER_INSERT_NHANVIEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_AFTER_INSERT_NHANVIEN" 
AFTER INSERT ON NHANVIEN
FOR EACH ROW
DECLARE
    v_tentk_base VARCHAR2(50);
    v_tentk VARCHAR2(50);
    v_matkhau VARCHAR2(50);

    -- H�m chuy?n ??i k� t? ti?ng Vi?t c� d?u th�nh kh�ng d?u
    FUNCTION convert_to_ascii(p_str IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN TRANSLATE(
            p_str,
            '����������������������������������????�����������������������������??',
            'AAAAAAACEEEEIIIIDNOOOOOOUUUUYBSaaaaaaaaaaceeeeiiiionoooooouuuuyyybyDd'
        );
    END convert_to_ascii;
BEGIN
    -- Chuy?n t�n nh�n vi�n th�nh kh�ng d?u, x�a kho?ng c�ch v� kh�ng vi?t in hoa
    v_tentk_base := LOWER(REPLACE(convert_to_ascii(:NEW.TENNV), ' ', ''));

    -- T?o t�i kho?n v� m?t kh?u c? b?n cho m?i nh�n vi�n
    v_tentk := v_tentk_base || :NEW.MANV;
    v_matkhau := v_tentk;
    INSERT INTO TAIKHOAN (TENTK, MANV, MATKHAU, LOAITK) VALUES (v_tentk, :NEW.MANV, v_matkhau, 0);

    -- N?u ch?c v? l� "Tr??ng ph�ng" v� ph�ng ban l� K? to�n ho?c Nh�n s?, t?o th�m t�i kho?n qu?n tr?
    IF :NEW.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' AND (:NEW.MAPB = 'PB03' OR :NEW.MAPB = 'PB04') THEN
        v_tentk := v_tentk_base || 'AD';
        v_matkhau := v_tentk;
        INSERT INTO TAIKHOAN (TENTK, MANV, MATKHAU, LOAITK) VALUES (v_tentk, :NEW.MANV, v_matkhau, 1);
    END IF;
END;
/
ALTER TRIGGER "TRG_AFTER_INSERT_NHANVIEN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_UPDATE_TAIKHOAN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UPDATE_TAIKHOAN" 
AFTER UPDATE OF CHUCVU ON NHANVIEN
FOR EACH ROW
DECLARE
    v_tentk_base VARCHAR2(50);
    v_tentk VARCHAR2(50);
    v_matkhau VARCHAR2(50);
    v_test CHAR(50);

    -- H�m chuy?n ??i k� t? ti?ng Vi?t c� d?u th�nh kh�ng d?u
    FUNCTION convert_to_ascii(p_str IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN TRANSLATE(
            p_str,
            '����������������������������������????�����������������������������??',
            'AAAAAAACEEEEIIIIDNOOOOOOUUUUYBSaaaaaaaaaaceeeeiiiionoooooouuuuyyybyDd'
        );
    END convert_to_ascii;

BEGIN
    -- Chuy?n t�n nh�n vi�n th�nh kh�ng d?u, x�a kho?ng c�ch v� kh�ng vi?t in hoa
    v_tentk_base := LOWER(REPLACE(convert_to_ascii(:NEW.TENNV), ' ', ''));
    v_test := v_tentk_base || 'AD';

    -- N?u ch?c v? thay ??i t? "Tr??ng ph�ng" th�nh c�c ch?c v? kh�c
    IF :OLD.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' AND :NEW.CHUCVU <> u'Tr\01b0\1edfng ph\00f2ng' THEN
        DELETE FROM PHIEUCHAMCONG WHERE MANV = :NEW.MANV;
        DELETE FROM YEUCAUNGHIPHEP WHERE MANV = :NEW.MANV;
        DELETE FROM YEUCAUUNGLUONG WHERE MANV = :NEW.MANV;
        DELETE FROM TAIKHOAN WHERE TENTK = v_test AND MANV = :NEW.MANV;
        DELETE FROM TRUONGPHONG WHERE MANV = :NEW.MANV;
    END IF;

    -- N?u ch?c v? thay ??i t? c�c ch?c v? kh�c th�nh "Tr??ng ph�ng" v� ph�ng ban h?p l?
    IF :OLD.CHUCVU != u'Tr\01b0\1edfng ph\00f2ng' AND :NEW.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' AND
       (:NEW.MAPB = 'PB03' OR :NEW.MAPB = 'PB04') THEN
        v_tentk := v_tentk_base || 'AD';
        v_matkhau := v_tentk;
        INSERT INTO TAIKHOAN (TENTK, MANV, MATKHAU, LOAITK) VALUES (v_tentk, :NEW.MANV, v_matkhau, 1);
        UPDATE TRUONGPHONG SET MANV = :NEW.MANV, NGAYNC = SYSDATE WHERE MAPB = :NEW.MAPB;
    END IF;

    -- C?p nh?t t�i kho?n c? b?n
    v_tentk := v_tentk_base || :NEW.MANV;
    v_matkhau := v_tentk;
    UPDATE TAIKHOAN
    SET TENTK = v_tentk, MATKHAU = v_matkhau
    WHERE MANV = :NEW.MANV AND LOAITK = 0;

    -- N?u ch?c v? hi?n t?i l� "Tr??ng ph�ng", c?p nh?t t�i kho?n qu?n tr?
    IF :NEW.CHUCVU = u'Tr\01b0\1edfng ph\00f2ng' THEN
        v_tentk := v_tentk_base || 'AD';
        v_matkhau := v_tentk;
        UPDATE TAIKHOAN
        SET TENTK = v_tentk, MATKHAU = v_matkhau
        WHERE MANV = :NEW.MANV AND LOAITK = 1;
    END IF;
END;
/
ALTER TRIGGER "TRG_UPDATE_TAIKHOAN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREVENT_DELETE_PHONGBAN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREVENT_DELETE_PHONGBAN" 
BEFORE DELETE ON PHONGBAN
FOR EACH ROW
DECLARE
    v_count PHONGBAN.MAPB%TYPE;
BEGIN

    SELECT COUNT(*) INTO v_count FROM NHANVIEN WHERE MAPB = :OLD.MAPB;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Kh�ng th? x�a ph�ng ban v� c� nh�n vi�n li�n k?t.');
    END IF;

    SELECT COUNT(*) INTO v_count FROM TRUONGPHONG WHERE MAPB = :OLD.MAPB;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Kh�ng th? x�a ph�ng ban v� c� tr??ng ph�ng li�n k?t.');
    END IF;
END;

/
ALTER TRIGGER "PREVENT_DELETE_PHONGBAN" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADD_BANGLUONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADD_BANGLUONG" (
    P_MANV IN NUMBER,
    P_NAM IN NUMBER,
    P_THANG IN NUMBER,
    P_TONGTIENUL IN NUMBER,
    P_LUONGTL IN NUMBER
)
IS
    MAX_MABL NUMBER;
BEGIN
    SELECT NVL(MAX(MABL), 0) + 1 INTO MAX_MABL FROM BANGLUONG;
    INSERT INTO BANGLUONG (MABL, MANV, NAM, THANG, TONGTIENUL, LUONGTL)
    VALUES (MAX_MABL, P_MANV, P_NAM, P_THANG, P_TONGTIENUL, P_LUONGTL);
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETEPHONGBAN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "DELETEPHONGBAN" (
    p_MAPB IN PHONGBAN.MAPB%TYPE
) IS
    v_max_SEQ NUMBER;
BEGIN
    DELETE FROM PHONGBAN WHERE MAPB = p_MAPB;

    SELECT MAX(TO_NUMBER(SUBSTR(MAPB, 3))) INTO v_max_SEQ FROM PHONGBAN;

    IF v_max_SEQ IS NULL THEN
        v_max_SEQ := 1;
    END IF;

    EXECUTE IMMEDIATE 'ALTER SEQUENCE PHONGBAN_SEQ RESTART START WITH ' || (v_max_SEQ + 1);
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20001 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Kh�ng th? x�a ph�ng ban v� c� nh�n vi�n li�n k?t.');
        ELSIF SQLCODE = -20002 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Kh�ng th? x�a ph�ng ban v� c� tr??ng ph�ng li�n k?t.');
        ELSE
            RAISE;
        END IF;
END;

/
--------------------------------------------------------
--  DDL for Procedure HUY_YEU_CAU_NGHI_PHEP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "HUY_YEU_CAU_NGHI_PHEP" (
  p_maycnp IN YEUCAUNGHIPHEP.MAYCNP%TYPE
) IS
  v_trangthai YEUCAUNGHIPHEP.TRANGTHAINP%TYPE;
BEGIN
  -- L?y tr?ng th�i hi?n t?i c?a y�u c?u ngh? ph�p
  SELECT TRANGTHAINP INTO v_trangthai
  FROM YEUCAUNGHIPHEP
  WHERE MAYCNP = p_maycnp;

  -- Ki?m tra xem y�u c?u ?� ???c ph� duy?t hay ch?a
  IF v_trangthai = u'\0110\00e3 ph\00ea duy\1ec7t' THEN
    RAISE_APPLICATION_ERROR(-20007, 'Kh�ng th? h?y y�u c?u ?� ???c ph� duy?t.');
  END IF;

  -- Ki?m tra xem y�u c?u ?� b? t? ch?i hay ch?a
  IF v_trangthai = u'T\1eeb ch\1ed1i' THEN
    RAISE_APPLICATION_ERROR(-20008, 'Kh�ng th? h?y y�u c?u ?� b? t? ch?i.');
  END IF;

  -- C?p nh?t tr?ng th�i y�u c?u th�nh "?� h?y"
  UPDATE YEUCAUNGHIPHEP
  SET TRANGTHAINP = u'\0110\00e3 h\1ee7y'
  WHERE MAYCNP = p_maycnp;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE(u'\0110\00e3 h\1ee7y y\00eau c\1ea7u ngh\1ec9 ph\00e9p c\00f3 m\00e3 ' || p_maycnp);

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('L?i: ' || SQLERRM);
END huy_yeu_cau_nghi_phep;

/
--------------------------------------------------------
--  DDL for Procedure HUY_YEU_CAU_UNG_LUONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "HUY_YEU_CAU_UNG_LUONG" (
  p_maycul IN YEUCAUUNGLUONG.MAYCUL%TYPE
) IS
  v_trangthai YEUCAUUNGLUONG.TRANGTHAIUL%TYPE;
BEGIN
  -- L?y tr?ng th�i hi?n t?i c?a y�u c?u ?ng l??ng
  SELECT TRANGTHAIUL INTO v_trangthai
  FROM YEUCAUUNGLUONG
  WHERE MAYCUL = p_maycul;

  -- Ki?m tra xem y�u c?u ?� ???c ph� duy?t hay ch?a
  IF v_trangthai = u'\0110\00e3 ph\00ea duy\1ec7t' THEN
    RAISE_APPLICATION_ERROR(-20009, 'Kh�ng th? h?y y�u c?u ?� ???c ph� duy?t.');
  END IF;

  -- Ki?m tra xem y�u c?u ?� b? t? ch?i hay ch?a
  IF v_trangthai = u'T\1eeb ch\1ed1i' THEN
    RAISE_APPLICATION_ERROR(-20010, 'Kh�ng th? h?y y�u c?u ?� b? t? ch?i.');
  END IF;

  -- C?p nh?t tr?ng th�i y�u c?u th�nh "?� h?y"
  UPDATE YEUCAUUNGLUONG
  SET TRANGTHAIUL = u'\0110\00e3 h\1ee7y'
  WHERE MAYCUL = p_maycul;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE(u'\0110\00e3 h\1ee7y y\00eau c\1ea7u \1ee9ng l\01b0\01a1ng c\00f3 m\00e3 ' || p_maycul);

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('L?i: ' || SQLERRM);
END huy_yeu_cau_ung_luong;

/
--------------------------------------------------------
--  DDL for Procedure INSERTPHONGBAN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "INSERTPHONGBAN" (
    p_TENPB IN VARCHAR2,
    p_NGAYTL IN DATE
) IS
    v_MAPB CHAR(4);
    v_SEQ NUMBER;
BEGIN
    SELECT PHONGBAN_SEQ.NEXTVAL INTO v_SEQ FROM DUAL;
    v_MAPB := 'PB' || LPAD(v_SEQ, 2, '0');

    INSERT INTO PHONGBAN (MAPB, TENPB, NGAYTL) VALUES (v_MAPB, p_TENPB, p_NGAYTL);
END;

/
--------------------------------------------------------
--  DDL for Procedure KIEM_TRA_NHAN_VIEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "KIEM_TRA_NHAN_VIEN" (
  p_manv IN NHANVIEN.MANV%TYPE,
  p_ton_tai OUT BOOLEAN
) IS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM NHANVIEN WHERE MANV = p_manv;

  IF v_count > 0 THEN
    p_ton_tai := TRUE;
  ELSE
    p_ton_tai := FALSE;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    p_ton_tai := FALSE; -- ??t p_ton_tai th�nh FALSE khi c� l?i
    RAISE;  -- V?n raise exception ?? th�ng b�o l?i
END kiem_tra_nhan_vien;

/
--------------------------------------------------------
--  DDL for Procedure SP_ADDNHANVIEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_ADDNHANVIEN" (
    p_MAPB IN CHAR,
    p_TENNV IN VARCHAR2,
    p_CCCD IN CHAR,
    p_NGSINH IN DATE,
    p_QUEQUAN IN VARCHAR2,
    p_GIOITINH IN SMALLINT,
    p_CHUCVU IN VARCHAR2,
    p_LUONGCB IN NUMBER,
    p_HESO IN FLOAT
) IS
    v_count INTEGER;
    v_age INTEGER;
BEGIN
    -- Ki?m tra xem nh�n vi�n ?� t?n t?i hay ch?a d?a tr�n CCCD
    SELECT COUNT(*) INTO v_count
    FROM NHANVIEN
    WHERE CCCD = p_CCCD;

    IF v_count = 0 THEN
        -- T�nh tu?i c?a nh�n vi�n
        SELECT TRUNC((SYSDATE - p_NGSINH) / 365.25) INTO v_age FROM DUAL;

        -- Ki?m tra n?u tu?i nh? h?n 18
        IF v_age < 18 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Nh�n vi�n ph?i ?? 18 tu?i.');
        END IF;

        -- Th�m nh�n vi�n m?i
        INSERT INTO NHANVIEN (MANV, MAPB, TENNV, CCCD, NGSINH, QUEQUAN, GIOITINH, CHUCVU, LUONGCB, HESO)
        VALUES (seq_nhanvien.NEXTVAL, p_MAPB, p_TENNV, p_CCCD, p_NGSINH, p_QUEQUAN, p_GIOITINH, p_CHUCVU, p_LUONGCB, p_HESO);
    ELSE
        -- N?u t?n t?i, th�ng b�o nh�n vi�n ?� t?n t?i v?i CCCD n�y
        RAISE_APPLICATION_ERROR(-20001, 'Nh�n vi�n ?� t?n t?i v?i CCCD n�y.');
    END IF;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_DELETENHANVIEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_DELETENHANVIEN" (
    p_MANV IN CHAR
) IS
BEGIN
    DELETE FROM TAIKHOAN WHERE MANV = p_MANV;
    DELETE FROM NHANVIEN WHERE MANV = p_MANV;
END;


/
--------------------------------------------------------
--  DDL for Procedure SP_UPDATENHANVIEN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_UPDATENHANVIEN" (
    p_MANV IN INTEGER,
    p_MAPB IN CHAR,
    p_TENNV IN VARCHAR2,
    p_CCCD IN CHAR,
    p_NGSINH IN DATE,
    p_QUEQUAN IN VARCHAR2,
    p_GIOITINH IN SMALLINT,
    p_CHUCVU IN VARCHAR2,
    p_LUONGCB IN NUMBER,
    p_HESO IN FLOAT
)
AS
    v_age INTEGER;
BEGIN
    -- T�nh tu?i c?a nh�n vi�n
    SELECT TRUNC((SYSDATE - p_NGSINH) / 365.25) INTO v_age FROM DUAL;

    -- Ki?m tra n?u tu?i nh? h?n 18
    IF v_age < 18 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Nh�n vi�n ph?i ?? 18 tu?i.');
    END IF;

    -- C?p nh?t th�ng tin nh�n vi�n
    UPDATE NHANVIEN
    SET MAPB = p_MAPB,
        TENNV = p_TENNV,
        CCCD = p_CCCD,
        NGSINH = p_NGSINH,
        QUEQUAN = p_QUEQUAN,
        GIOITINH = p_GIOITINH,
        CHUCVU = p_CHUCVU,
        LUONGCB = p_LUONGCB,
        HESO = p_HESO
    WHERE MANV = p_MANV;
END;


/
--------------------------------------------------------
--  DDL for Procedure THEM_PHIEU_CHAM_CONG_THEO_NGAY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "THEM_PHIEU_CHAM_CONG_THEO_NGAY" (
  p_manv IN PHIEUCHAMCONG.MANV%TYPE,
  p_ngchamcong IN PHIEUCHAMCONG.NGAYCC%TYPE -- S?a t�n c?t
) IS
  v_maphieu PHIEUCHAMCONG.MAPCC%TYPE;
  v_ton_tai_nhan_vien BOOLEAN;
  v_da_cham_cong NUMBER; 
BEGIN
  -- Ki?m tra s? t?n t?i c?a nh�n vi�n
  kiem_tra_nhan_vien(p_manv, v_ton_tai_nhan_vien);

  IF NOT v_ton_tai_nhan_vien THEN
    RAISE_APPLICATION_ERROR(-20004, 'Nh�n vi�n kh�ng t?n t?i.');
  END IF;

  -- Ki?m tra xem nh�n vi�n ?� ch?m c�ng trong ng�y ch?a
  SELECT COUNT(*) INTO v_da_cham_cong
  FROM PHIEUCHAMCONG
  WHERE MANV = p_manv AND TRUNC(NGAYCC) = TRUNC(p_ngchamcong); -- S?a t�n c?t

  IF v_da_cham_cong > 0 THEN
    RAISE_APPLICATION_ERROR(-20005, 'Nh�n vi�n ?� ch?m c�ng trong ng�y n�y.');
  END IF;

  -- L?y MAPHIEU l?n nh?t hi?n t?i v� t?ng th�m 1
  SELECT COALESCE(MAX(MAPCC), 0) + 1 INTO v_maphieu FROM PHIEUCHAMCONG;

  -- Th�m d? li?u v�o b?ng PHIEUCHAMCONG
  INSERT INTO PHIEUCHAMCONG (MAPCC, MANV, NGAYCC)
  VALUES (v_maphieu, p_manv, p_ngchamcong); -- S?a t�n c?t

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END them_phieu_cham_cong_theo_ngay;

/
--------------------------------------------------------
--  DDL for Procedure SP_XULYEUCAUNGHIPHEP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_XULYEUCAUNGHIPHEP" (
  IN_MAYCNP IN YEUCAUNGHIPHEP.MAYCNP%TYPE,
  IN_FLAG   IN INT
) IS
  V_DAYDIFF    INT;
  V_DAYBEGIN   DATE;
  V_DAYEND     DATE;
  V_TRANGTHAI  YEUCAUNGHIPHEP.TRANGTHAINP%TYPE;
  V_MANV       NHANVIEN.MANV%TYPE;
BEGIN
  -- L?y th�ng tin ng�y b?t ??u, ng�y k?t th�c, tr?ng th�i v� m� nh�n vi�n c?a y�u c?u ngh? ph�p
  SELECT NGAYBD, NGAYKT, TRANGTHAINP, MANV
  INTO V_DAYBEGIN, V_DAYEND, V_TRANGTHAI, V_MANV
  FROM YEUCAUNGHIPHEP
  WHERE MAYCNP = IN_MAYCNP;

  -- Ki?m tra xem y�u c?u ?� ???c x? l� tr??c ?� hay ch?a
  IF V_TRANGTHAI IN (u'\0110\00e3 ph\00ea duy\1ec7t', u'T\1eeb ch\1ed1i') THEN
    RAISE_APPLICATION_ERROR(-20089, u'Y\00eau c\1ea7u \0111\00e3 \0111\01b0\1ee3c x\1eed l\00fd tr\01b0\1edbc \0111\00f3.');
  END IF;

  -- T�nh s? ng�y ngh? ph�p (ch? t�nh ph?n nguy�n)
  V_DAYDIFF := TRUNC(V_DAYEND) - TRUNC(V_DAYBEGIN) + 1;

  -- C?p nh?t tr?ng th�i y�u c?u ngh? ph�p
  IF IN_FLAG = 1 THEN
    UPDATE YEUCAUNGHIPHEP SET TRANGTHAINP = u'\0110\00e3 ph\00ea duy\1ec7t' WHERE MAYCNP = IN_MAYCNP;
  ELSE
    UPDATE YEUCAUNGHIPHEP SET TRANGTHAINP = u'T\1eeb ch\1ed1i' WHERE MAYCNP = IN_MAYCNP;
  END IF;

  -- Th�m phi?u ch?m c�ng cho t?ng ng�y ngh? (n?u ???c ph� duy?t)
  IF IN_FLAG = 1 THEN
    FOR i IN 0 .. V_DAYDIFF - 1 LOOP
      -- Th�m phi?u ch?m c�ng
      them_phieu_cham_cong_theo_ngay(V_MANV, TRUNC(V_DAYBEGIN) + i);
    END LOOP;
  END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE(u'X\1eed l\00fd y\00eau c\1ea7u ngh\1ec9 ph\00e9p th\00e0nh c\00f4ng.');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('L?i: ' || SQLERRM);
END SP_XULYEUCAUNGHIPHEP;

/
--------------------------------------------------------
--  DDL for Procedure SP_XULYEUCAUUNGLUONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_XULYEUCAUUNGLUONG" (
  IN_MAYCUL IN YEUCAUUNGLUONG.MAYCUL%TYPE,
  IN_FLAG   IN INT
) IS
  V_COUNTCHECK INT;
  V_TRANGTHAI  YEUCAUUNGLUONG.TRANGTHAIUL%TYPE;
BEGIN
  -- Ki?m tra tr?ng th�i hi?n t?i c?a y�u c?u ?ng l??ng
  SELECT TRANGTHAIUL 
  INTO V_TRANGTHAI
  FROM YEUCAUUNGLUONG
  WHERE MAYCUL = IN_MAYCUL;

  -- Ki?m tra xem y�u c?u ?� ???c x? l� tr??c ?� hay ch?a
  IF V_TRANGTHAI IN (u'\0110\00e3 ph\00ea duy\1ec7t', u'T\1eeb ch\1ed1i') THEN
    RAISE_APPLICATION_ERROR(-20088, u'Y\00eau c\1ea7u \0111\00e3 \0111\01b0\1ee3c x\1eed l\00fd tr\01b0\1edbc \0111\00f3.');
  END IF;

  -- C?p nh?t tr?ng th�i y�u c?u ?ng l??ng
  IF IN_FLAG = 1 THEN
    UPDATE YEUCAUUNGLUONG SET TRANGTHAIUL = u'\0110\00e3 ph\00ea duy\1ec7t' WHERE MAYCUL = IN_MAYCUL;
  ELSE
    UPDATE YEUCAUUNGLUONG SET TRANGTHAIUL = u'T\1eeb ch\1ed1i' WHERE MAYCUL = IN_MAYCUL;
  END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('X? l� y�u c?u ?ng l??ng th�nh c�ng.');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('L?i: ' || SQLERRM);
END SP_XULYEUCAUUNGLUONG;

/
--------------------------------------------------------
--  DDL for Procedure THEM_PHIEU_CHAM_CONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "THEM_PHIEU_CHAM_CONG" (
  p_manv IN PHIEUCHAMCONG.MANV%TYPE
) IS
  v_maphieu PHIEUCHAMCONG.MAPCC%TYPE;
  v_ton_tai_nhan_vien BOOLEAN;
  v_da_cham_cong NUMBER; -- Thay ??i ki?u d? li?u t? BOOLEAN th�nh NUMBER
BEGIN
  -- Ki?m tra s? t?n t?i c?a nh�n vi�n
  kiem_tra_nhan_vien(p_manv, v_ton_tai_nhan_vien);

  IF NOT v_ton_tai_nhan_vien THEN
    RAISE_APPLICATION_ERROR(-20004, 'Nh�n vi�n kh�ng t?n t?i.');
  END IF;

  -- Ki?m tra xem nh�n vi�n ?� ch?m c�ng trong ng�y h�m nay ch?a
  SELECT COUNT(*) INTO v_da_cham_cong -- G�n k?t qu? COUNT(*) v�o v_da_cham_cong
  FROM PHIEUCHAMCONG
  WHERE MANV = p_manv AND TRUNC(NGAYCC) = TRUNC(SYSDATE);

  IF v_da_cham_cong > 0 THEN -- So s�nh v?i 0 thay v� g�n tr?c ti?p
    RAISE_APPLICATION_ERROR(-20005, 'Nh�n vi�n ?� ch?m c�ng trong ng�y h�m nay.');
  END IF;

  -- L?y MAPHIEU l?n nh?t hi?n t?i v� t?ng th�m 1
  SELECT COALESCE(MAX(MAPCC), 0) + 1 INTO v_maphieu FROM PHIEUCHAMCONG;

  -- Th�m d? li?u v�o b?ng PHIEUCHAMCONG
  INSERT INTO PHIEUCHAMCONG (MAPCC, MANV, NGAYCC)
  VALUES (v_maphieu, p_manv, SYSDATE); 

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END them_phieu_cham_cong;

/

--------------------------------------------------------
--  DDL for Procedure UPDATEPHONGBAN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "UPDATEPHONGBAN" (
    p_MAPB IN PHONGBAN.MAPB % TYPE,
    p_TENPB IN PHONGBAN.TENPB % TYPE,
    p_NGAYTL IN DATE
) IS
BEGIN
    UPDATE PHONGBAN
    SET TENPB = p_TENPB,
        NGAYTL = p_NGAYTL
    WHERE MAPB = p_MAPB;
END;

/
--------------------------------------------------------
--  DDL for Procedure XOA_PHIEU_CHAM_CONG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XOA_PHIEU_CHAM_CONG" (
  p_maphieu IN PHIEUCHAMCONG.MAPCC%TYPE
) IS
BEGIN
  -- Ki?m tra xem phi?u ch?m c�ng c� t?n t?i hay kh�ng
  FOR rec IN (SELECT 1 FROM PHIEUCHAMCONG WHERE MAPCC = p_maphieu) LOOP
    -- X�a phi?u ch?m c�ng
    DELETE FROM PHIEUCHAMCONG WHERE MAPCC = p_maphieu;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('?� x�a phi?u ch?m c�ng c� m� ' || p_maphieu);
    RETURN; -- Tho�t kh?i procedure sau khi x�a
  END LOOP;

  -- N?u kh�ng t�m th?y phi?u ch?m c�ng
  RAISE_APPLICATION_ERROR(-20006, 'Kh�ng t�m th?y phi?u ch?m c�ng c� m� ' || p_maphieu);
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END xoa_phieu_cham_cong;

/
--------------------------------------------------------
--  DDL for Function TIM_MANV
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "TIM_MANV" (p_TENTK IN TAIKHOAN.TENTK%TYPE)
RETURN TAIKHOAN.MANV%TYPE
AS
    v_MANV TAIKHOAN.MANV%TYPE;
BEGIN
    SELECT MANV INTO v_MANV FROM TAIKHOAN WHERE TENTK = p_TENTK;
    RETURN v_MANV;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END Tim_MaNV;

/
--------------------------------------------------------
--  DDL for Function TONG_YEU_CAU_UNG_LUONG_TRONG_THANG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "TONG_YEU_CAU_UNG_LUONG_TRONG_THANG" (
  p_manv IN YEUCAUUNGLUONG.MANV%TYPE
) RETURN NUMBER IS
  v_tong NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_tong
  FROM YEUCAUUNGLUONG
  WHERE MANV = p_manv
    AND EXTRACT(MONTH FROM NGAYUL) = EXTRACT(MONTH FROM SYSDATE) -- So s�nh v?i th�ng hi?n t?i
    AND EXTRACT(YEAR FROM NGAYUL) = EXTRACT(YEAR FROM SYSDATE)-- So s�nh v?i n?m hi?n t?i
    AND TRANGTHAIUL = u'\0110\00e3 ph\00ea duy\1ec7t'; -- Ch? t�nh y�u c?u ?� ph� duy?t

  RETURN v_tong;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0; -- Tr? v? 0 n?u kh�ng t�m th?y y�u c?u n�o
  WHEN OTHERS THEN
    RAISE; -- N�m l?i exception n?u c� l?i kh�c
END tong_yeu_cau_ung_luong_trong_thang;

/
--------------------------------------------------------
--  Constraints for Table BANGLUONG
--------------------------------------------------------

  ALTER TABLE "BANGLUONG" MODIFY ("MABL" NOT NULL ENABLE);
  ALTER TABLE "BANGLUONG" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "BANGLUONG" MODIFY ("NAM" NOT NULL ENABLE);
  ALTER TABLE "BANGLUONG" MODIFY ("THANG" NOT NULL ENABLE);
  ALTER TABLE "BANGLUONG" MODIFY ("TONGTIENUL" NOT NULL ENABLE);
  ALTER TABLE "BANGLUONG" MODIFY ("LUONGTL" NOT NULL ENABLE);
  ALTER TABLE "BANGLUONG" ADD CONSTRAINT "PK_BANGLUONG" PRIMARY KEY ("MABL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "NHANVIEN" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("MAPB" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("TENNV" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("CCCD" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("NGSINH" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("QUEQUAN" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("GIOITINH" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("CHUCVU" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("LUONGCB" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" MODIFY ("HESO" NOT NULL ENABLE);
  ALTER TABLE "NHANVIEN" ADD CONSTRAINT "PK_NHANVIEN" PRIMARY KEY ("MANV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHIEUCHAMCONG
--------------------------------------------------------

  ALTER TABLE "PHIEUCHAMCONG" MODIFY ("MAPCC" NOT NULL ENABLE);
  ALTER TABLE "PHIEUCHAMCONG" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "PHIEUCHAMCONG" MODIFY ("NGAYCC" NOT NULL ENABLE);
  ALTER TABLE "PHIEUCHAMCONG" ADD CONSTRAINT "PK_PHIEUCHAMCONG" PRIMARY KEY ("MAPCC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHONGBAN
--------------------------------------------------------

  ALTER TABLE "PHONGBAN" MODIFY ("MAPB" NOT NULL ENABLE);
  ALTER TABLE "PHONGBAN" MODIFY ("TENPB" NOT NULL ENABLE);
  ALTER TABLE "PHONGBAN" MODIFY ("NGAYTL" NOT NULL ENABLE);
  ALTER TABLE "PHONGBAN" ADD CONSTRAINT "PK_PHONGBAN" PRIMARY KEY ("MAPB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAIKHOAN
--------------------------------------------------------

  ALTER TABLE "TAIKHOAN" MODIFY ("TENTK" NOT NULL ENABLE);
  ALTER TABLE "TAIKHOAN" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "TAIKHOAN" MODIFY ("MATKHAU" NOT NULL ENABLE);
  ALTER TABLE "TAIKHOAN" MODIFY ("LOAITK" NOT NULL ENABLE);
  ALTER TABLE "TAIKHOAN" ADD CONSTRAINT "PK_TAIKHOAN" PRIMARY KEY ("TENTK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRUONGPHONG
--------------------------------------------------------

  ALTER TABLE "TRUONGPHONG" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "TRUONGPHONG" MODIFY ("MAPB" NOT NULL ENABLE);
  ALTER TABLE "TRUONGPHONG" MODIFY ("NGAYNC" NOT NULL ENABLE);
  ALTER TABLE "TRUONGPHONG" ADD CONSTRAINT "PK_TRUONGPHONG" PRIMARY KEY ("MANV", "MAPB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table YEUCAUNGHIPHEP
--------------------------------------------------------

  ALTER TABLE "YEUCAUNGHIPHEP" MODIFY ("MAYCNP" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUNGHIPHEP" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUNGHIPHEP" MODIFY ("NGAYGUI" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUNGHIPHEP" MODIFY ("NGAYBD" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUNGHIPHEP" MODIFY ("NGAYKT" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUNGHIPHEP" MODIFY ("GHICHUNP" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUNGHIPHEP" MODIFY ("TRANGTHAINP" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUNGHIPHEP" ADD CONSTRAINT "PK_YEUCAUNGHIPHEP" PRIMARY KEY ("MAYCNP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table YEUCAUUNGLUONG
--------------------------------------------------------

  ALTER TABLE "YEUCAUUNGLUONG" MODIFY ("MAYCUL" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUUNGLUONG" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUUNGLUONG" MODIFY ("NGAYUL" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUUNGLUONG" MODIFY ("TIENUL" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUUNGLUONG" MODIFY ("GHICHUUL" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUUNGLUONG" MODIFY ("TRANGTHAIUL" NOT NULL ENABLE);
  ALTER TABLE "YEUCAUUNGLUONG" ADD CONSTRAINT "PK_YEUCAUUNGLUONG" PRIMARY KEY ("MAYCUL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANGLUONG
--------------------------------------------------------

  ALTER TABLE "BANGLUONG" ADD CONSTRAINT "FK_BANGLUON_SOHUU_NHANVIEN" FOREIGN KEY ("MANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "NHANVIEN" ADD CONSTRAINT "FK_NHANVIEN_LAMVIEC_PHONGBAN" FOREIGN KEY ("MAPB")
	  REFERENCES "PHONGBAN" ("MAPB") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHIEUCHAMCONG
--------------------------------------------------------

  ALTER TABLE "PHIEUCHAMCONG" ADD CONSTRAINT "FK_PHIEUCHA_KHAIBAO_NHANVIEN" FOREIGN KEY ("MANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAIKHOAN
--------------------------------------------------------

  ALTER TABLE "TAIKHOAN" ADD CONSTRAINT "FK_TAIKHOAN_DUOCCAP_NHANVIEN" FOREIGN KEY ("MANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRUONGPHONG
--------------------------------------------------------

  ALTER TABLE "TRUONGPHONG" ADD CONSTRAINT "FK_TRUONGPH_TRUONGPHO_NHANVIEN" FOREIGN KEY ("MANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
  ALTER TABLE "TRUONGPHONG" ADD CONSTRAINT "FK_TRUONGPH_TRUONGPHO_PHONGBAN" FOREIGN KEY ("MAPB")
	  REFERENCES "PHONGBAN" ("MAPB") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table YEUCAUNGHIPHEP
--------------------------------------------------------

  ALTER TABLE "YEUCAUNGHIPHEP" ADD CONSTRAINT "FK_YEUCAUNG_GUI_NHANVIEN" FOREIGN KEY ("MANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table YEUCAUUNGLUONG
--------------------------------------------------------

  ALTER TABLE "YEUCAUUNGLUONG" ADD CONSTRAINT "FK_YEUCAUUN_THUCHIEN_NHANVIEN" FOREIGN KEY ("MANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
