/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package USER;
import DAO.access_YEUCAUNGHIPHEP;
import DAO.access_YEUCAUUNGLUONG;
import DTO.PHIEUCHAMCONG;
import DTO.*;
import DTO.Connect;
import USER.Login.DangNhapForm;
import java.awt.Color;
import java.util.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Phuc
 */
public class Home extends javax.swing.JFrame {
    DefaultTableModel YeuCauNghiPhepTm;
        DefaultTableModel YeuCauUngLuongTm;
    /**
     * Creates new form HomeCopy
     */
    Calendar c;
    Connection con;
    int YeuCauCreating=0;
    String[] ngay = {"","Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy"};

    public Home() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println(info.getClassName());
                    break;
                }
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        c = Calendar.getInstance(TimeZone.getTimeZone("Asia/Ho_Chi_Minh"));
        con = Connect.connect();
        initComponents();
        BangLuongHandler();
        ChamCongHandler();
        BChamCongHandler();
        YeuCauNghiPhepTbHandler();
        YeuCauUngLuongTbHandler();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        LbManHinhChinh = new javax.swing.JLabel();
        LbLichSuChamCong = new javax.swing.JLabel();
        LbYeuCau = new javax.swing.JLabel();
        LbBangLuong = new javax.swing.JLabel();
        LbUsername = new javax.swing.JLabel();
        PnContainer = new javax.swing.JPanel();
        JtpContent = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        LbChao = new javax.swing.JLabel();
        LbNgayThangNam = new javax.swing.JLabel();
        BChamCong = new javax.swing.JButton();
        LbBuoiIcon = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ChamCongThanhCongLb = new javax.swing.JLabel();
        LichSuChamCongPanel = new javax.swing.JPanel();
        TbChamCong = new javax.swing.JScrollPane();
        ChamCongTb = new Component.myTable();
        TimLichSuChamCongTf = new javax.swing.JTextField();
        TimLichSuChamCongBtn = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        BangLuongPanel = new javax.swing.JPanel();
        TbBangLuong = new javax.swing.JScrollPane();
        BangLuongTb = new Component.myTable();
        TimBangLuongTf = new javax.swing.JTextField();
        TimBangLuongBtn = new javax.swing.JButton();
        CbBangLuong = new javax.swing.JComboBox<>();
        YeuCauPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BtnYeuCauNghiPhep = new javax.swing.JButton();
        BtnYeuCauUngLuong = new javax.swing.JButton();
        YeuCauTb = new javax.swing.JTabbedPane();
        YeuCauNghiPhepPanel = new javax.swing.JPanel();
        TbChamCong1 = new javax.swing.JScrollPane();
        YeuCauNghiPhepTb = new Component.myTable();
        TimYeuCauNghiPhepTf = new javax.swing.JTextField();
        TimYeuCauNghiPhepBtn = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        GuiYeuCauNghiPhepBtn = new javax.swing.JButton();
        YeuCauUngLuongPanel = new javax.swing.JPanel();
        TbChamCong2 = new javax.swing.JScrollPane();
        YeuCauUngLuongTb = new Component.myTable();
        TimYeuCauUngLuongTf = new javax.swing.JTextField();
        TimYeuCauUngLuongBtn = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        GuiYeuCauUngLuongBtn = new javax.swing.JButton();
        GuiYeuCauNghiPhepPanel = new javax.swing.JPanel();
        HuyGuiYeuCauBtn1 = new javax.swing.JButton();
        XacNhanYeuCauNghiPhepBtn = new javax.swing.JButton();
        NgayBatDauChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NgayKetThucChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LyDoNghiPhepTa = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        GuiYeuCauUngLuongPanel = new javax.swing.JPanel();
        HuyGuiYeuCauBtn2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        XacNhanYeuCauUngLuongBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        LyDoUngLuongTf = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SoTienUngTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 768));
        setResizable(false);

        Header.setBackground(java.awt.Color.white);
        Header.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 251, 251), 1, true));
        Header.setPreferredSize(new java.awt.Dimension(0, 60));

        LbManHinhChinh.setBackground(java.awt.Color.white);
        LbManHinhChinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbManHinhChinh.setForeground(new java.awt.Color(38, 103, 255));
        LbManHinhChinh.setText("Màn hình chính");
        LbManHinhChinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbManHinhChinhMouseClicked(evt);
            }
        });

        LbLichSuChamCong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbLichSuChamCong.setText("Lịch sử chấm công");
        LbLichSuChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbLichSuChamCongMouseClicked(evt);
            }
        });

        LbYeuCau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbYeuCau.setText("Yêu cầu");
        LbYeuCau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbYeuCauMouseClicked(evt);
            }
        });

        LbBangLuong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbBangLuong.setText("Bảng lương");
        LbBangLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbBangLuongMouseClicked(evt);
            }
        });

        LbUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbUsername.setText("Đăng xuất");
        LbUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbUsernameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(LbManHinhChinh)
                .addGap(18, 18, 18)
                .addComponent(LbLichSuChamCong)
                .addGap(18, 18, 18)
                .addComponent(LbBangLuong)
                .addGap(18, 18, 18)
                .addComponent(LbYeuCau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbLichSuChamCong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addComponent(LbBangLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LbYeuCau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LbManHinhChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PnContainer.setBackground(new java.awt.Color(255, 255, 255));
        PnContainer.setAutoscrolls(true);
        PnContainer.setMaximumSize(new java.awt.Dimension(2147483647, 700));
        PnContainer.setMinimumSize(new java.awt.Dimension(1287, 700));
        PnContainer.setPreferredSize(new java.awt.Dimension(1280, 700));
        PnContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JtpContent.setToolTipText("");

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setPreferredSize(new java.awt.Dimension(1280, 655));

        LbChao.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LbChao.setText(getBuoi());

        LbNgayThangNam.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        LbNgayThangNam.setText(ngay[c.get(Calendar.DAY_OF_WEEK)]+", ngày " +c.get(Calendar.DATE)+" Tháng " + (c.get(Calendar.MONTH)+1)+" năm "+ c.get(Calendar.YEAR));

        BChamCong.setBackground(new java.awt.Color(34, 103, 255));
        BChamCong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BChamCong.setForeground(new java.awt.Color(255, 255, 255));
        BChamCong.setText("Bắt đầu chấm công cho hôm nay");
        BChamCong.setFocusPainted(false);
        BChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BChamCongActionPerformed(evt);
            }
        });

        LbBuoiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(getBuoiIcon())));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        ChamCongThanhCongLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ChamCongThanhCongLb.setText("Bạn đã chấm công cho hôm nay thành công");
        ChamCongThanhCongLb.setVisible(false);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbNgayThangNam)
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addComponent(LbChao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbBuoiIcon))))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(BChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChamCongThanhCongLb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(LbChao, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(LbBuoiIcon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbNgayThangNam)
                .addGap(107, 107, 107)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChamCongThanhCongLb))
                .addGap(138, 138, 138)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        BChamCong.getAccessibleContext().setAccessibleName("BChamCong");
        BChamCong.getAccessibleContext().setAccessibleDescription("Bắt đầu chấm công cho hôm nay");

        JtpContent.addTab("tab5", HomePanel);

        LichSuChamCongPanel.setBackground(new java.awt.Color(255, 255, 255));

        ChamCongTb.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Mã số", "Ngày chấm công","Thời gian vào"
            }
        ));
        ChamCongTb.setGridColor(new java.awt.Color(255, 255, 255));
        TbChamCong.setViewportView(ChamCongTb);

        TimLichSuChamCongTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimLichSuChamCongTfActionPerformed(evt);
            }
        });

        TimLichSuChamCongBtn.setBackground(new java.awt.Color(34, 103, 255));
        TimLichSuChamCongBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TimLichSuChamCongBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimLichSuChamCongBtn.setText("Tìm");
        TimLichSuChamCongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimLichSuChamCongBtnActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã số" }));
        jComboBox2.setBackground(Color.WHITE);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LichSuChamCongPanelLayout = new javax.swing.GroupLayout(LichSuChamCongPanel);
        LichSuChamCongPanel.setLayout(LichSuChamCongPanelLayout);
        LichSuChamCongPanelLayout.setHorizontalGroup(
            LichSuChamCongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LichSuChamCongPanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(LichSuChamCongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(LichSuChamCongPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimLichSuChamCongTf, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimLichSuChamCongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TbChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        LichSuChamCongPanelLayout.setVerticalGroup(
            LichSuChamCongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LichSuChamCongPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(LichSuChamCongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimLichSuChamCongTf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimLichSuChamCongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TbChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        JtpContent.addTab("tab7", LichSuChamCongPanel);

        BangLuongPanel.setBackground(new java.awt.Color(255, 255, 255));

        BangLuongTb.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Mã số", "Tháng", "Số ngày công", "Phép/Không Phép","Tiền ứng trước","Thưởng tăng ca","Lương cơ bản","Lương thực lãnh"
            }
        ));
        BangLuongTb.setGridColor(new java.awt.Color(255, 255, 255));
        TbBangLuong.setViewportView(BangLuongTb);

        TimBangLuongTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimBangLuongTfActionPerformed(evt);
            }
        });

        TimBangLuongBtn.setBackground(new java.awt.Color(34, 103, 255));
        TimBangLuongBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TimBangLuongBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimBangLuongBtn.setText("Tìm");
        TimBangLuongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimBangLuongBtnActionPerformed(evt);
            }
        });

        CbBangLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã số" }));
        CbBangLuong.setBackground(Color.WHITE);
        CbBangLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbBangLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BangLuongPanelLayout = new javax.swing.GroupLayout(BangLuongPanel);
        BangLuongPanel.setLayout(BangLuongPanelLayout);
        BangLuongPanelLayout.setHorizontalGroup(
            BangLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BangLuongPanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(BangLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(BangLuongPanelLayout.createSequentialGroup()
                        .addComponent(CbBangLuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimBangLuongTf, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimBangLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TbBangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        BangLuongPanelLayout.setVerticalGroup(
            BangLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BangLuongPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BangLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimBangLuongTf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimBangLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbBangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TbBangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        JtpContent.addTab("tab7", BangLuongPanel);

        YeuCauPanel.setBackground(new java.awt.Color(255, 255, 255));
        YeuCauPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnYeuCauNghiPhep.setBackground(new java.awt.Color(34, 103, 255));
        BtnYeuCauNghiPhep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnYeuCauNghiPhep.setForeground(new java.awt.Color(255, 255, 255));
        BtnYeuCauNghiPhep.setText("Yêu Cầu Nghỉ Phép");
        BtnYeuCauNghiPhep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYeuCauNghiPhepActionPerformed(evt);
            }
        });

        BtnYeuCauUngLuong.setBackground(new java.awt.Color(34, 103, 255));
        BtnYeuCauUngLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnYeuCauUngLuong.setForeground(new java.awt.Color(255, 255, 255));
        BtnYeuCauUngLuong.setText("Yêu Cầu Ứng Lương");
        BtnYeuCauUngLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYeuCauUngLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnYeuCauNghiPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnYeuCauUngLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(964, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnYeuCauNghiPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnYeuCauUngLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        YeuCauPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 60));

        YeuCauNghiPhepPanel.setBackground(new java.awt.Color(255, 255, 255));

        YeuCauNghiPhepTb.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Mã số", "Ngày gửi","Ngày bắt đầu","Ngày kết thúc","Lý do","Trạng thái"
            }
        ));
        YeuCauNghiPhepTb.setGridColor(new java.awt.Color(255, 255, 255));
        YeuCauNghiPhepTb.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                YeuCauNghiPhepTbMouseDragged(evt);
            }
        });
        YeuCauNghiPhepTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YeuCauNghiPhepTbMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                YeuCauNghiPhepTbMousePressed(evt);
            }
        });
        TbChamCong1.setViewportView(YeuCauNghiPhepTb);

        TimYeuCauNghiPhepTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimYeuCauNghiPhepTfActionPerformed(evt);
            }
        });

        TimYeuCauNghiPhepBtn.setBackground(new java.awt.Color(34, 103, 255));
        TimYeuCauNghiPhepBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TimYeuCauNghiPhepBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimYeuCauNghiPhepBtn.setText("Tìm");
        TimYeuCauNghiPhepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimYeuCauNghiPhepBtnActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã số" }));
        jComboBox3.setBackground(Color.WHITE);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        GuiYeuCauNghiPhepBtn.setBackground(new java.awt.Color(34, 103, 255));
        GuiYeuCauNghiPhepBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GuiYeuCauNghiPhepBtn.setForeground(new java.awt.Color(255, 255, 255));
        GuiYeuCauNghiPhepBtn.setText("Gửi yêu cầu mới");
        GuiYeuCauNghiPhepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiYeuCauNghiPhepBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout YeuCauNghiPhepPanelLayout = new javax.swing.GroupLayout(YeuCauNghiPhepPanel);
        YeuCauNghiPhepPanel.setLayout(YeuCauNghiPhepPanelLayout);
        YeuCauNghiPhepPanelLayout.setHorizontalGroup(
            YeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YeuCauNghiPhepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(YeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YeuCauNghiPhepPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimYeuCauNghiPhepTf, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TimYeuCauNghiPhepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GuiYeuCauNghiPhepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TbChamCong1, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        YeuCauNghiPhepPanelLayout.setVerticalGroup(
            YeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YeuCauNghiPhepPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(YeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimYeuCauNghiPhepTf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimYeuCauNghiPhepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuiYeuCauNghiPhepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TbChamCong1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        YeuCauTb.addTab("tab1", YeuCauNghiPhepPanel);

        YeuCauUngLuongPanel.setBackground(new java.awt.Color(255, 255, 255));

        YeuCauUngLuongTb.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Mã số", "Ngày gửi","Số tiền ứng","Lý do","Trạng thái"
            }
        ));
        YeuCauUngLuongTb.setGridColor(new java.awt.Color(255, 255, 255));
        YeuCauUngLuongTb.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                YeuCauUngLuongTbMouseDragged(evt);
            }
        });
        TbChamCong2.setViewportView(YeuCauUngLuongTb);

        TimYeuCauUngLuongTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimYeuCauUngLuongTfActionPerformed(evt);
            }
        });

        TimYeuCauUngLuongBtn.setBackground(new java.awt.Color(34, 103, 255));
        TimYeuCauUngLuongBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TimYeuCauUngLuongBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimYeuCauUngLuongBtn.setText("Tìm");
        TimYeuCauUngLuongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimYeuCauUngLuongBtnActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã số" }));
        jComboBox4.setBackground(Color.WHITE);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        GuiYeuCauUngLuongBtn.setBackground(new java.awt.Color(34, 103, 255));
        GuiYeuCauUngLuongBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GuiYeuCauUngLuongBtn.setForeground(new java.awt.Color(255, 255, 255));
        GuiYeuCauUngLuongBtn.setText("Gửi yêu cầu mới");
        GuiYeuCauUngLuongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiYeuCauUngLuongBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout YeuCauUngLuongPanelLayout = new javax.swing.GroupLayout(YeuCauUngLuongPanel);
        YeuCauUngLuongPanel.setLayout(YeuCauUngLuongPanelLayout);
        YeuCauUngLuongPanelLayout.setHorizontalGroup(
            YeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YeuCauUngLuongPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(YeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YeuCauUngLuongPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimYeuCauUngLuongTf, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TimYeuCauUngLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GuiYeuCauUngLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TbChamCong2, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        YeuCauUngLuongPanelLayout.setVerticalGroup(
            YeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YeuCauUngLuongPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(YeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimYeuCauUngLuongTf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimYeuCauUngLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuiYeuCauUngLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TbChamCong2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        YeuCauTb.addTab("tab1", YeuCauUngLuongPanel);

        GuiYeuCauNghiPhepPanel.setBackground(new java.awt.Color(255, 255, 255));

        HuyGuiYeuCauBtn1.setBackground(new java.awt.Color(34, 103, 255));
        HuyGuiYeuCauBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HuyGuiYeuCauBtn1.setForeground(new java.awt.Color(255, 255, 255));
        HuyGuiYeuCauBtn1.setText("Huỷ bỏ");
        HuyGuiYeuCauBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyGuiYeuCauBtn1ActionPerformed(evt);
            }
        });

        XacNhanYeuCauNghiPhepBtn.setBackground(new java.awt.Color(34, 103, 255));
        XacNhanYeuCauNghiPhepBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        XacNhanYeuCauNghiPhepBtn.setForeground(new java.awt.Color(255, 255, 255));
        XacNhanYeuCauNghiPhepBtn.setText("Gửi yêu cầu");
        XacNhanYeuCauNghiPhepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XacNhanYeuCauNghiPhepBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Gửi yêu cầu nghỉ phép");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Chọn ngày bắt đầu");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Lý do nghỉ phép");

        LyDoNghiPhepTa.setColumns(20);
        LyDoNghiPhepTa.setRows(5);
        jScrollPane1.setViewportView(LyDoNghiPhepTa);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Chọn ngày kết thúc");

        javax.swing.GroupLayout GuiYeuCauNghiPhepPanelLayout = new javax.swing.GroupLayout(GuiYeuCauNghiPhepPanel);
        GuiYeuCauNghiPhepPanel.setLayout(GuiYeuCauNghiPhepPanelLayout);
        GuiYeuCauNghiPhepPanelLayout.setHorizontalGroup(
            GuiYeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiYeuCauNghiPhepPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HuyGuiYeuCauBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(XacNhanYeuCauNghiPhepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(GuiYeuCauNghiPhepPanelLayout.createSequentialGroup()
                .addGroup(GuiYeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GuiYeuCauNghiPhepPanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(GuiYeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(GuiYeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(NgayBatDauChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NgayKetThucChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane1))))
                    .addGroup(GuiYeuCauNghiPhepPanelLayout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(jLabel1)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        GuiYeuCauNghiPhepPanelLayout.setVerticalGroup(
            GuiYeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiYeuCauNghiPhepPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NgayBatDauChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NgayKetThucChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(GuiYeuCauNghiPhepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XacNhanYeuCauNghiPhepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuyGuiYeuCauBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        YeuCauTb.addTab("tab3", GuiYeuCauNghiPhepPanel);

        GuiYeuCauUngLuongPanel.setBackground(new java.awt.Color(255, 255, 255));

        HuyGuiYeuCauBtn2.setBackground(new java.awt.Color(34, 103, 255));
        HuyGuiYeuCauBtn2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HuyGuiYeuCauBtn2.setForeground(new java.awt.Color(255, 255, 255));
        HuyGuiYeuCauBtn2.setText("Huỷ bỏ");
        HuyGuiYeuCauBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyGuiYeuCauBtn2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Lý do ứng lương");

        XacNhanYeuCauUngLuongBtn.setBackground(new java.awt.Color(34, 103, 255));
        XacNhanYeuCauUngLuongBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        XacNhanYeuCauUngLuongBtn.setForeground(new java.awt.Color(255, 255, 255));
        XacNhanYeuCauUngLuongBtn.setText("Gửi yêu cầu");
        XacNhanYeuCauUngLuongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XacNhanYeuCauUngLuongBtnActionPerformed(evt);
            }
        });

        LyDoUngLuongTf.setColumns(20);
        LyDoUngLuongTf.setRows(5);
        jScrollPane2.setViewportView(LyDoUngLuongTf);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Gửi yêu cầu ứng lương");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Nhập số tiền cần ứng");

        SoTienUngTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SoTienUngTfKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setText("VND");

        javax.swing.GroupLayout GuiYeuCauUngLuongPanelLayout = new javax.swing.GroupLayout(GuiYeuCauUngLuongPanel);
        GuiYeuCauUngLuongPanel.setLayout(GuiYeuCauUngLuongPanelLayout);
        GuiYeuCauUngLuongPanelLayout.setHorizontalGroup(
            GuiYeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiYeuCauUngLuongPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HuyGuiYeuCauBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(XacNhanYeuCauUngLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(GuiYeuCauUngLuongPanelLayout.createSequentialGroup()
                .addGroup(GuiYeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GuiYeuCauUngLuongPanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(GuiYeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GuiYeuCauUngLuongPanelLayout.createSequentialGroup()
                                .addComponent(SoTienUngTf, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))))
                    .addGroup(GuiYeuCauUngLuongPanelLayout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(jLabel7)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        GuiYeuCauUngLuongPanelLayout.setVerticalGroup(
            GuiYeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiYeuCauUngLuongPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GuiYeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SoTienUngTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(GuiYeuCauUngLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XacNhanYeuCauUngLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuyGuiYeuCauBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        YeuCauTb.addTab("tab4", GuiYeuCauUngLuongPanel);

        YeuCauPanel.add(YeuCauTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1290, 710));

        JtpContent.addTab("tab7", YeuCauPanel);

        PnContainer.add(JtpContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1290, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbManHinhChinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbManHinhChinhMouseClicked
        JtpContent.setSelectedIndex(0);
        setMenuColors();
        LbManHinhChinh.setForeground(new java.awt.Color(38, 103, 255));

    }//GEN-LAST:event_LbManHinhChinhMouseClicked

    private void LbLichSuChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbLichSuChamCongMouseClicked
        JtpContent.setSelectedIndex(1);
        setMenuColors();
        LbLichSuChamCong.setForeground(new java.awt.Color(38, 103, 255));

    }//GEN-LAST:event_LbLichSuChamCongMouseClicked

    private void LbYeuCauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbYeuCauMouseClicked
        JtpContent.setSelectedIndex(3);
        setMenuColors();
        LbYeuCau.setForeground(new java.awt.Color(38, 103, 255));

    }//GEN-LAST:event_LbYeuCauMouseClicked

    private void LbBangLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbBangLuongMouseClicked
        JtpContent.setSelectedIndex(2);
        setMenuColors();
        LbBangLuong.setForeground(new java.awt.Color(38, 103, 255));
    }//GEN-LAST:event_LbBangLuongMouseClicked

    private void LbUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbUsernameMouseClicked
        int choice = JOptionPane.showConfirmDialog(null, "Bạn muốn đăng xuất khỏi hệ thống ?", "Xác nhận đăng xuất", JOptionPane.YES_NO_OPTION);
        if( choice == JOptionPane.YES_OPTION)
        {
            DangNhapForm loginForm = new DangNhapForm();
            this.dispose();
            loginForm.setVisible(true);
        }
    }//GEN-LAST:event_LbUsernameMouseClicked

    private void TimBangLuongTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimBangLuongTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimBangLuongTfActionPerformed

    private void TimBangLuongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimBangLuongBtnActionPerformed
            String keyword = TimBangLuongTf.getText();
            RowFilter<Object, Object> rf;
            if (keyword.trim().isEmpty()) {
                rf = null;
            } else {
                rf = RowFilter.regexFilter( keyword, 0);
            }
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) BangLuongTb.getModel());
            sorter.setRowFilter(rf);
            BangLuongTb.setRowSorter(sorter);
    }//GEN-LAST:event_TimBangLuongBtnActionPerformed

    private void CbBangLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbBangLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbBangLuongActionPerformed

    private void TimLichSuChamCongTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimLichSuChamCongTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimLichSuChamCongTfActionPerformed

    private void TimLichSuChamCongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimLichSuChamCongBtnActionPerformed
            String keyword = TimLichSuChamCongTf.getText();
            RowFilter<Object, Object> rf;
            if (keyword.trim().isEmpty()) {
                rf = null;
            } else {
                rf = RowFilter.regexFilter( keyword, 0);
            }
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) ChamCongTb.getModel());
            sorter.setRowFilter(rf);
            ChamCongTb.setRowSorter(sorter);
    }//GEN-LAST:event_TimLichSuChamCongBtnActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void BtnYeuCauNghiPhepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYeuCauNghiPhepActionPerformed
        YeuCauTb.setSelectedIndex(YeuCauCreating+0);
    }//GEN-LAST:event_BtnYeuCauNghiPhepActionPerformed

    private void BtnYeuCauUngLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYeuCauUngLuongActionPerformed
        YeuCauTb.setSelectedIndex(YeuCauCreating+1);
    }//GEN-LAST:event_BtnYeuCauUngLuongActionPerformed

    private void TimYeuCauNghiPhepTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimYeuCauNghiPhepTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimYeuCauNghiPhepTfActionPerformed

    private void TimYeuCauNghiPhepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimYeuCauNghiPhepBtnActionPerformed
            String keyword = TimYeuCauNghiPhepTf.getText();
            RowFilter<Object, Object> rf;
            if (keyword.trim().isEmpty()) {
                rf = null;
            } else {
                rf = RowFilter.regexFilter( keyword, 0);
            }
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) YeuCauNghiPhepTb.getModel());
            sorter.setRowFilter(rf);
            YeuCauNghiPhepTb.setRowSorter(sorter);  
    }//GEN-LAST:event_TimYeuCauNghiPhepBtnActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void GuiYeuCauNghiPhepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiYeuCauNghiPhepBtnActionPerformed
        YeuCauTb.setSelectedIndex(2);
        YeuCauCreating=2;
        
    }//GEN-LAST:event_GuiYeuCauNghiPhepBtnActionPerformed

    private void TimYeuCauUngLuongTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimYeuCauUngLuongTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimYeuCauUngLuongTfActionPerformed

    private void TimYeuCauUngLuongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimYeuCauUngLuongBtnActionPerformed
            String keyword = TimYeuCauUngLuongTf.getText();
            RowFilter<Object, Object> rf;
            if (keyword.trim().isEmpty()) {
                rf = null;
            } else {
                rf = RowFilter.regexFilter( keyword, 0);
            }
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) YeuCauUngLuongTb.getModel());
            sorter.setRowFilter(rf);
            YeuCauUngLuongTb.setRowSorter(sorter);
    }//GEN-LAST:event_TimYeuCauUngLuongBtnActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void GuiYeuCauUngLuongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiYeuCauUngLuongBtnActionPerformed
        try(Connection con = Connect.connect();PreparedStatement statement = con.prepareStatement("SELECT tong_yeu_cau_ung_luong_trong_thang(?) AS TONG FROM DUAL")){
            statement.setInt(1,User.USERID);
            ResultSet rs = statement.executeQuery();
            if(rs.next()){
                int TongYeuCau = rs.getInt(1);
                if(TongYeuCau>=2){
                    JOptionPane.showMessageDialog(this, "Bạn đã gửi đủ 2 yêu cầu trong tháng này", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }catch(Exception e){
                System.out.println(e);
        }
        YeuCauTb.setSelectedIndex(3);
        YeuCauCreating=2;
    }//GEN-LAST:event_GuiYeuCauUngLuongBtnActionPerformed

    private void BChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BChamCongActionPerformed
        PHIEUCHAMCONG.ChamCongHomNay(User.USERID);
            ChamCongThanhCongLb.setVisible(true);
            BChamCong.setVisible(false);
                    ChamCongHandler();

    }//GEN-LAST:event_BChamCongActionPerformed

    private void HuyGuiYeuCauBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyGuiYeuCauBtn1ActionPerformed
        YeuCauCreating=0;
        YeuCauTb.setSelectedIndex(YeuCauTb.getSelectedIndex()-2);
    }//GEN-LAST:event_HuyGuiYeuCauBtn1ActionPerformed

    private void XacNhanYeuCauNghiPhepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XacNhanYeuCauNghiPhepBtnActionPerformed
        if(NgayBatDauChooser.getCalendar()==null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày bắt đầu", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else if (NgayKetThucChooser.getCalendar()==null){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày kết thúc", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else if(NgayBatDauChooser.getCalendar().compareTo(Calendar.getInstance())<0){
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải lớn hơn ngày hiện tại", "Lỗi", JOptionPane.ERROR_MESSAGE);

        }
        else if(NgayBatDauChooser.getCalendar().compareTo(NgayKetThucChooser.getCalendar())>0){
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải lớn hơn ngày kết thúc", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            access_YEUCAUNGHIPHEP.GuiYeuCauNghiPhep(User.USERID, NgayBatDauChooser.getCalendar(), NgayKetThucChooser.getCalendar(), LyDoNghiPhepTa.getText()+" ");
            JOptionPane.showMessageDialog(this, "Gửi yêu cầu thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            LyDoNghiPhepTa.setText("");
            NgayBatDauChooser.setDate(null);
            NgayKetThucChooser.setDate(null);
            YeuCauNghiPhepTbHandler();
        }
        
    }//GEN-LAST:event_XacNhanYeuCauNghiPhepBtnActionPerformed

    private void HuyGuiYeuCauBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyGuiYeuCauBtn2ActionPerformed
        YeuCauCreating=0;
        YeuCauTb.setSelectedIndex(YeuCauTb.getSelectedIndex()-2);    }//GEN-LAST:event_HuyGuiYeuCauBtn2ActionPerformed

    private void XacNhanYeuCauUngLuongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XacNhanYeuCauUngLuongBtnActionPerformed
        if(SoTienUngTf.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền cần ứng", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            try(Connection con = Connect.connect(); PreparedStatement statement = con.prepareStatement("SELECT LUONGCB FROM NHANVIEN WHERE MANV=?")){
            statement.setInt(1,User.USERID);
            ResultSet rs = statement.executeQuery();
            if(rs.next()){
                int LuongCB = rs.getInt(1);
                System.out.println((SoTienUngTf.getText())+"va"+LuongCB);
                if((LuongCB/10)<(Integer.parseInt(SoTienUngTf.getText()))){
                    JOptionPane.showMessageDialog(this, "Số tiền ứng không được quá 10% mức lương cơ bản. Lương cơ bản của bạn: "+LuongCB, "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }catch(Exception e){
                System.out.println(e);
        }
            access_YEUCAUUNGLUONG.GuiYeuCauUngLuong(User.USERID,Integer.parseInt(SoTienUngTf.getText()), LyDoUngLuongTf.getText()+" ");
            JOptionPane.showMessageDialog(this, "Gửi yêu cầu thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            SoTienUngTf.setText("");
            LyDoUngLuongTf.setText("");
            YeuCauUngLuongTbHandler();
        }

    }//GEN-LAST:event_XacNhanYeuCauUngLuongBtnActionPerformed

    private void SoTienUngTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoTienUngTfKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_SoTienUngTfKeyTyped

    private void YeuCauNghiPhepTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YeuCauNghiPhepTbMouseClicked
    }//GEN-LAST:event_YeuCauNghiPhepTbMouseClicked

    private void YeuCauNghiPhepTbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YeuCauNghiPhepTbMousePressed
    }//GEN-LAST:event_YeuCauNghiPhepTbMousePressed

    private void YeuCauNghiPhepTbMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YeuCauNghiPhepTbMouseDragged
        if(YeuCauNghiPhepTm.getValueAt(YeuCauNghiPhepTb.getSelectedRow(),5).toString().compareTo("Chờ phê duyệt")==0)    
        {
            int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn huỷ yêu cầu được chọn ?", "Huỷ yêu cầu", JOptionPane.YES_NO_OPTION);
            if( choice == JOptionPane.YES_OPTION)
            {
                access_YEUCAUNGHIPHEP.HuyYeuCau(Integer.parseInt(YeuCauNghiPhepTm.getValueAt(YeuCauNghiPhepTb.getSelectedRow(),0).toString()));
                YeuCauNghiPhepTbHandler();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_YeuCauNghiPhepTbMouseDragged

    private void YeuCauUngLuongTbMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YeuCauUngLuongTbMouseDragged
        if(YeuCauUngLuongTm.getValueAt(YeuCauUngLuongTb.getSelectedRow(),4).toString().compareTo("Chờ phê duyệt")==0)    
        {
            int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn huỷ yêu cầu được chọn ?", "Huỷ yêu cầu", JOptionPane.YES_NO_OPTION);
            if( choice == JOptionPane.YES_OPTION)
            {
                access_YEUCAUUNGLUONG.HuyYeuCau(Integer.parseInt(YeuCauUngLuongTm.getValueAt(YeuCauUngLuongTb.getSelectedRow(),0).toString()));
                YeuCauUngLuongTbHandler();
            }
        }    }//GEN-LAST:event_YeuCauUngLuongTbMouseDragged
    private void BChamCongHandler(){
        if(PHIEUCHAMCONG.TinhTrangChamCong(User.USERID, c.get(Calendar.DATE), c.get(Calendar.MONTH) + 1, c.get(Calendar.YEAR))){
            ChamCongThanhCongLb.setVisible(true);
            BChamCong.setVisible(false);
        }
    }
    private String getBuoi(){
        int hour = c.get(Calendar.HOUR_OF_DAY);
        if(hour>6&&hour<=11) return "Chào buổi sáng";
        else if(hour>11&&hour<=14) return "Chào buổi trưa";
        else if(hour>14&&hour<18) return "Chào buổi chiều";
        else  return "Chào buổi tối";
    }
    private String getBuoiIcon(){
        int hour = c.get(Calendar.HOUR_OF_DAY);
        if(hour>6&&hour<18) return "/Resources/mattroipng.png";
        else return "/Resources/mattrang.png";
    }
    private void setMenuColors(){
        LbManHinhChinh.setForeground(new java.awt.Color(0, 0, 0));
        LbLichSuChamCong.setForeground(new java.awt.Color(0, 0, 0));
        LbYeuCau.setForeground(new java.awt.Color(0, 0, 0));
        LbBangLuong.setForeground(new java.awt.Color(0, 0, 0));
        LbUsername.setForeground(new java.awt.Color(0, 0, 0));        
    }

    private void BangLuongHandler(){
        DefaultTableModel defaultTable = new DefaultTableModel();
        defaultTable.setColumnIdentifiers(new String [] {
        "Mã số", "Tháng", "Tiền ứng trước","Lương thực lãnh"
    });
        
                String sql= "SELECT *FROM BANGLUONG where MANV=?";
                try(PreparedStatement statement = con.prepareStatement(sql)){
                    statement.setInt(1,User.USERID);
                    ResultSet rs= statement.executeQuery();
                    while(rs.next()){
                    String[] row = new String[4];        
                    row[0]=rs.getString(1);
                    row[1]=rs.getString("Thang")+"/"+rs.getString("Nam");
                    row[2]=rs.getString("TONGTIENUL");
                    row[3]=rs.getString("LUONGTL");
                    defaultTable.addRow(row);
                    }
                }catch(SQLException e1){
                    System.out.println("Loi"+ e1);
                }        
        BangLuongTb.setModel(defaultTable);
    }
        private void ChamCongHandler(){
        DefaultTableModel defaultTable = new DefaultTableModel();
        defaultTable.setColumnIdentifiers(new String [] {
         "Mã số", "Ngày chấm công"
         });
        ArrayList<PHIEUCHAMCONG> al = PHIEUCHAMCONG.getPhieuChamCong();
        for(PHIEUCHAMCONG p: al){
            String[] row = new String[2];
            row[0]=Integer.toString(p.getMAPCC());
            row[1]=p.getNgay()+"/"+p.getThang()+"/"+p.getNam();
            defaultTable.addRow(row);
        }
        ChamCongTb.setModel(defaultTable);
    }
        private void YeuCauNghiPhepTbHandler(){
        YeuCauNghiPhepTm = new DefaultTableModel();
        YeuCauNghiPhepTm.setColumnIdentifiers(new String [] {
        "Mã số", "Ngày gửi","Ngày bắt đầu","Ngày kết thúc","Lý do","Trạng thái"
    });    
        ArrayList<YEUCAUNGHIPHEP> al = access_YEUCAUNGHIPHEP.getYeuCauNghiPhep();
            for(YEUCAUNGHIPHEP y: al){
                String[] row = new String[6];
                row[0]=Integer.toString(y.getMaYC());
                row[1]=y.getStringNgayGui();
                row[2]=y.getStringNgayBD();
                row[3]=y.getStringNgayKT();
                row[4]=y.getLyDo();
                row[5]=y.getTrangThai();
                YeuCauNghiPhepTm.addRow(row);
            }
            YeuCauNghiPhepTb.setModel(YeuCauNghiPhepTm);

        }
        
private void YeuCauUngLuongTbHandler() {
    YeuCauUngLuongTm = new DefaultTableModel();
    YeuCauUngLuongTm.setColumnIdentifiers(new String[]{
        "Mã số", "Ngày gửi", "Số tiền ứng", "Ghi chú", "Trạng thái"
    });

    ArrayList<YEUCAUUNGLUONG> al = access_YEUCAUUNGLUONG.getYeuCauUngLuong();
    for (YEUCAUUNGLUONG y : al) {
        String[] row = new String[5];
        row[0] = Integer.toString(y.getMaYC());
        row[1] = y.getStringNgayGui();
        row[2] = Long.toString(y.getTienUng()); 
        row[3] = y.getGhiChu();
        row[4] = y.getTrangThai();
        YeuCauUngLuongTm.addRow(row);
    }

    YeuCauUngLuongTb.setModel(YeuCauUngLuongTm);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BChamCong;
    private javax.swing.JPanel BangLuongPanel;
    private Component.myTable BangLuongTb;
    private javax.swing.JButton BtnYeuCauNghiPhep;
    private javax.swing.JButton BtnYeuCauUngLuong;
    private javax.swing.JComboBox<String> CbBangLuong;
    private Component.myTable ChamCongTb;
    private javax.swing.JLabel ChamCongThanhCongLb;
    private javax.swing.JButton GuiYeuCauNghiPhepBtn;
    private javax.swing.JPanel GuiYeuCauNghiPhepPanel;
    private javax.swing.JButton GuiYeuCauUngLuongBtn;
    private javax.swing.JPanel GuiYeuCauUngLuongPanel;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton HuyGuiYeuCauBtn1;
    private javax.swing.JButton HuyGuiYeuCauBtn2;
    private javax.swing.JTabbedPane JtpContent;
    private javax.swing.JLabel LbBangLuong;
    private javax.swing.JLabel LbBuoiIcon;
    private javax.swing.JLabel LbChao;
    private javax.swing.JLabel LbLichSuChamCong;
    private javax.swing.JLabel LbManHinhChinh;
    private javax.swing.JLabel LbNgayThangNam;
    private javax.swing.JLabel LbUsername;
    private javax.swing.JLabel LbYeuCau;
    private javax.swing.JPanel LichSuChamCongPanel;
    private javax.swing.JTextArea LyDoNghiPhepTa;
    private javax.swing.JTextArea LyDoUngLuongTf;
    private com.toedter.calendar.JDateChooser NgayBatDauChooser;
    private com.toedter.calendar.JDateChooser NgayKetThucChooser;
    private javax.swing.JPanel PnContainer;
    private javax.swing.JTextField SoTienUngTf;
    private javax.swing.JScrollPane TbBangLuong;
    private javax.swing.JScrollPane TbChamCong;
    private javax.swing.JScrollPane TbChamCong1;
    private javax.swing.JScrollPane TbChamCong2;
    private javax.swing.JButton TimBangLuongBtn;
    private javax.swing.JTextField TimBangLuongTf;
    private javax.swing.JButton TimLichSuChamCongBtn;
    private javax.swing.JTextField TimLichSuChamCongTf;
    private javax.swing.JButton TimYeuCauNghiPhepBtn;
    private javax.swing.JTextField TimYeuCauNghiPhepTf;
    private javax.swing.JButton TimYeuCauUngLuongBtn;
    private javax.swing.JTextField TimYeuCauUngLuongTf;
    private javax.swing.JButton XacNhanYeuCauNghiPhepBtn;
    private javax.swing.JButton XacNhanYeuCauUngLuongBtn;
    private javax.swing.JPanel YeuCauNghiPhepPanel;
    private Component.myTable YeuCauNghiPhepTb;
    private javax.swing.JPanel YeuCauPanel;
    private javax.swing.JTabbedPane YeuCauTb;
    private javax.swing.JPanel YeuCauUngLuongPanel;
    private Component.myTable YeuCauUngLuongTb;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
