/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ADMIN;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author ADMIN
 */
public class GiaoDienAdmin1 extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienAdmin
     */
    public GiaoDienAdmin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        lbQLNV = new javax.swing.JLabel();
        lbQuanLyPB = new javax.swing.JLabel();
        lbQuanLyCC = new javax.swing.JLabel();
        lbQLYCNP = new javax.swing.JLabel();
        lbQLYCTL = new javax.swing.JLabel();
        lbQLTC = new javax.swing.JLabel();
        lbTinhLuong = new javax.swing.JLabel();
        lbGDChung = new javax.swing.JLabel();
        tabController = new javax.swing.JTabbedPane();
        panelDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelQLNV = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelQLPB = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelQLCC = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelQLYCNP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelQLYCUL = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelQLTC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelTinhLuong = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setPreferredSize(new java.awt.Dimension(225, 768));

        lbQLNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/employee.png"))); // NOI18N
        lbQLNV.setText("Quản lý nhân viên");
        lbQLNV.setIconTextGap(12);
        lbQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQLNVMouseClicked(evt);
            }
        });

        lbQuanLyPB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQuanLyPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/department.png"))); // NOI18N
        lbQuanLyPB.setText("Quản lý phòng ban");
        lbQuanLyPB.setIconTextGap(12);
        lbQuanLyPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyPBMouseClicked(evt);
            }
        });

        lbQuanLyCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQuanLyCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/timesheets.png"))); // NOI18N
        lbQuanLyCC.setText("Quản lý chấm công");
        lbQuanLyCC.setIconTextGap(12);
        lbQuanLyCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyCCMouseClicked(evt);
            }
        });

        lbQLYCNP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQLYCNP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/contract.png"))); // NOI18N
        lbQLYCNP.setText("Quản lý YCNP");
        lbQLYCNP.setIconTextGap(12);
        lbQLYCNP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQLYCNPMouseClicked(evt);
            }
        });

        lbQLYCTL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQLYCTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/contract.png"))); // NOI18N
        lbQLYCTL.setText("Quản lý YCTL");
        lbQLYCTL.setIconTextGap(12);
        lbQLYCTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQLYCTLMouseClicked(evt);
            }
        });

        lbQLTC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQLTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/recruitment.png"))); // NOI18N
        lbQLTC.setText("Quản lý tăng ca");
        lbQLTC.setIconTextGap(12);
        lbQLTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQLTCMouseClicked(evt);
            }
        });

        lbTinhLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/salary.png"))); // NOI18N
        lbTinhLuong.setText("Tính lương");
        lbTinhLuong.setIconTextGap(12);
        lbTinhLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTinhLuongMouseClicked(evt);
            }
        });

        lbGDChung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbGDChung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuIMG/home.png"))); // NOI18N
        lbGDChung.setText("Màn hình chung");
        lbGDChung.setIconTextGap(12);
        lbGDChung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbGDChungMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbGDChung, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQLYCTL, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQLYCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuanLyCC, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuanLyPB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lbGDChung, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbQuanLyPB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbQuanLyCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbQLYCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbQLYCTL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbQLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        getContentPane().add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tabController.setBackground(new java.awt.Color(204, 204, 255));
        tabController.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabController.setPreferredSize(new java.awt.Dimension(1030, 768));

        panelDashboard.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setText("0");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(839, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        tabController.addTab("tab1", panelDashboard);

        panelQLNV.setBackground(new java.awt.Color(51, 51, 255));

        jLabel3.setText("1");

        javax.swing.GroupLayout panelQLNVLayout = new javax.swing.GroupLayout(panelQLNV);
        panelQLNV.setLayout(panelQLNVLayout);
        panelQLNVLayout.setHorizontalGroup(
            panelQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLNVLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(931, Short.MAX_VALUE))
        );
        panelQLNVLayout.setVerticalGroup(
            panelQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLNVLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel3)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        tabController.addTab("tab2", panelQLNV);

        panelQLPB.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setText("2");

        javax.swing.GroupLayout panelQLPBLayout = new javax.swing.GroupLayout(panelQLPB);
        panelQLPB.setLayout(panelQLPBLayout);
        panelQLPBLayout.setHorizontalGroup(
            panelQLPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLPBLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(782, Short.MAX_VALUE))
        );
        panelQLPBLayout.setVerticalGroup(
            panelQLPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLPBLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel8)
                .addContainerGap(557, Short.MAX_VALUE))
        );

        tabController.addTab("tab3", panelQLPB);

        panelQLCC.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setText("3");

        javax.swing.GroupLayout panelQLCCLayout = new javax.swing.GroupLayout(panelQLCC);
        panelQLCC.setLayout(panelQLCCLayout);
        panelQLCCLayout.setHorizontalGroup(
            panelQLCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLCCLayout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(701, Short.MAX_VALUE))
        );
        panelQLCCLayout.setVerticalGroup(
            panelQLCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLCCLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel7)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        tabController.addTab("tab4", panelQLCC);

        panelQLYCNP.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setText("4");

        javax.swing.GroupLayout panelQLYCNPLayout = new javax.swing.GroupLayout(panelQLYCNP);
        panelQLYCNP.setLayout(panelQLYCNPLayout);
        panelQLYCNPLayout.setHorizontalGroup(
            panelQLYCNPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLYCNPLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(775, Short.MAX_VALUE))
        );
        panelQLYCNPLayout.setVerticalGroup(
            panelQLYCNPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLYCNPLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel6)
                .addContainerGap(541, Short.MAX_VALUE))
        );

        tabController.addTab("tab5", panelQLYCNP);

        panelQLYCUL.setBackground(new java.awt.Color(153, 153, 0));

        jLabel5.setText("5");

        javax.swing.GroupLayout panelQLYCULLayout = new javax.swing.GroupLayout(panelQLYCUL);
        panelQLYCUL.setLayout(panelQLYCULLayout);
        panelQLYCULLayout.setHorizontalGroup(
            panelQLYCULLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLYCULLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(839, Short.MAX_VALUE))
        );
        panelQLYCULLayout.setVerticalGroup(
            panelQLYCULLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLYCULLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel5)
                .addContainerGap(555, Short.MAX_VALUE))
        );

        tabController.addTab("tab6", panelQLYCUL);

        panelQLTC.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setText("6");

        javax.swing.GroupLayout panelQLTCLayout = new javax.swing.GroupLayout(panelQLTC);
        panelQLTC.setLayout(panelQLTCLayout);
        panelQLTCLayout.setHorizontalGroup(
            panelQLTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLTCLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(944, Short.MAX_VALUE))
        );
        panelQLTCLayout.setVerticalGroup(
            panelQLTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLTCLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel2)
                .addContainerGap(589, Short.MAX_VALUE))
        );

        tabController.addTab("tab7", panelQLTC);

        jLabel4.setText("7");

        javax.swing.GroupLayout panelTinhLuongLayout = new javax.swing.GroupLayout(panelTinhLuong);
        panelTinhLuong.setLayout(panelTinhLuongLayout);
        panelTinhLuongLayout.setHorizontalGroup(
            panelTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTinhLuongLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(894, Short.MAX_VALUE))
        );
        panelTinhLuongLayout.setVerticalGroup(
            panelTinhLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTinhLuongLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel4)
                .addContainerGap(471, Short.MAX_VALUE))
        );

        tabController.addTab("tab8", panelTinhLuong);

        getContentPane().add(tabController, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1190, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQLNVMouseClicked
        tabController.setSelectedIndex(1);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
    }//GEN-LAST:event_lbQLNVMouseClicked

    private void lbQuanLyPBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyPBMouseClicked
        tabController.setSelectedIndex(2);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
    }//GEN-LAST:event_lbQuanLyPBMouseClicked

    private void lbQuanLyCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyCCMouseClicked
        tabController.setSelectedIndex(3);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
    }//GEN-LAST:event_lbQuanLyCCMouseClicked

    private void lbQLYCNPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQLYCNPMouseClicked
        tabController.setSelectedIndex(4);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
    }//GEN-LAST:event_lbQLYCNPMouseClicked

    private void lbQLYCTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQLYCTLMouseClicked
        tabController.setSelectedIndex(5);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
    }//GEN-LAST:event_lbQLYCTLMouseClicked

    private void lbQLTCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQLTCMouseClicked
        tabController.setSelectedIndex(6);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
    }//GEN-LAST:event_lbQLTCMouseClicked

    private void lbTinhLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTinhLuongMouseClicked
        tabController.setSelectedIndex(7);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
        
    }//GEN-LAST:event_lbTinhLuongMouseClicked

    private void lbGDChungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGDChungMouseClicked
        
        tabController.setSelectedIndex(0);
        changeLabelColor(menuBar);
        JLabel currentLabel = (JLabel)evt.getSource();
        currentLabel.setForeground(new Color(34,103,255));
        
        Component tab = tabController.getComponentAt(0);
        if(tab instanceof JPanel) 
         {
               JPanel panel = (JPanel)tab;
               Dashboard ds = new Dashboard();
               Component oldPanel = tabController.getSelectedComponent();
                tabController.setComponentAt(tabController.indexOfComponent(oldPanel), ds);
                tabController.validate();
                tabController.repaint();
         }
         
    }//GEN-LAST:event_lbGDChungMouseClicked

    public void changeLabelColor( JPanel panel){
        for(Component c : panel.getComponents())
            if( c  instanceof JLabel)
            {
                JLabel label = (JLabel)c;
                label.setForeground(new Color(0, 0, 0));
            }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienAdmin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbGDChung;
    private javax.swing.JLabel lbQLNV;
    private javax.swing.JLabel lbQLTC;
    private javax.swing.JLabel lbQLYCNP;
    private javax.swing.JLabel lbQLYCTL;
    private javax.swing.JLabel lbQuanLyCC;
    private javax.swing.JLabel lbQuanLyPB;
    private javax.swing.JLabel lbTinhLuong;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelQLCC;
    private javax.swing.JPanel panelQLNV;
    private javax.swing.JPanel panelQLPB;
    private javax.swing.JPanel panelQLTC;
    private javax.swing.JPanel panelQLYCNP;
    private javax.swing.JPanel panelQLYCUL;
    private javax.swing.JPanel panelTinhLuong;
    private javax.swing.JTabbedPane tabController;
    // End of variables declaration//GEN-END:variables
}


