package ADMIN;

import javax.swing.table.*;
import Data.JDBCConnection;
import java.sql.Connection;
import java.sql.*;
import java.util.*;

/**
 *
 * @author ADMIN
 */
public class QLCCForm extends javax.swing.JPanel {
    
    DefaultTableModel defaultTable;
    DefaultTableCellRenderer rendertbQLKyCong;
    
    /**
     * Creates new form QLCCForm
     */
    public QLCCForm() {
        initComponents();

    }
    
    
    /*
    public void TaoBangQLKC()
    {
        ArrayList<KYCONG> dsKyCong = getKYCONG();
        defaultTable= new DefaultTableModel();
        String columnNames[] = {"STT" , "Mã kỳ công", "Tháng", "Năm", "Ngày bắt đầu", "Ngày công tháng"};
        defaultTable.setColumnIdentifiers(columnNames);
         int index =1 ;
        for( KYCONG tmp : dsKyCong)
        {
            defaultTable.addRow(new Object[]{
                index,
                tmp.getMaKyCong(),
                tmp.getNam(),
                tmp.getThang(),
                tmp.getNgayTinhCong(),
                tmp.getTongNgayCongThang()
            });
            index ++;
        }
        
         tbQLKyCong.setModel(defaultTable);
        
        setVisible(true);
    }
    
    private ArrayList<KYCONG> getKYCONG()
    {
        Connection conn = new JDBCConnection().getJDBCConnection();
        ArrayList<KYCONG> lstKYCONG = new ArrayList<>();
        try
        {
            String query = "SELECT * FROM KYCONG";
            Statement st  = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                KYCONG tmp = new KYCONG();
                java.sql.Date ngayBatDau = rs.getObject("NGTC", java.sql.Date.class);
                
                tmp.setMaKyCong(rs.getString("MAKC"));
                tmp.setNam(Integer.parseInt(rs.getString("NAM")));
                tmp.setThang(Integer.parseInt(rs.getString("THANG")));
                tmp.setTongNgayCongThang(Integer.parseInt(rs.getString("SLGNGCONG")));
                
                if (ngayBatDau != null) 
                    tmp.setNgayTinhCong(ngayBatDau.toLocalDate());
                else
                    tmp.setNgayTinhCong(null);
                
                lstKYCONG.add(tmp);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        return lstKYCONG; 
    }
    */
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1055, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
